// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.client.verification
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;

pub const ServerSessionReadyEvent = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ClientIdRequest = struct {
    id: ManagedString = .Empty,

    pub const _desc_table = .{
        .id = fd(1, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ServerVerificationEvent = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ClientChallengeInitRequest = struct {
    challengeKey: ManagedString = .Empty,

    pub const _desc_table = .{
        .challengeKey = fd(1, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ServerChallengeEvent = struct {
    value: ?ManagedString = null,

    pub const _desc_table = .{
        .value = fd(1, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ClientChallengeProofRequest = struct {
    proof: ManagedString = .Empty,

    pub const _desc_table = .{
        .proof = fd(1, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
