// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.admin.console
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;

pub const ConsoleCommand = struct {
    content: ManagedString = .Empty,
    quiet: bool = false,

    pub const _desc_table = .{
        .content = fd(1, .String),
        .quiet = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ConsoleEnd = struct {
    success: bool = false,

    pub const _desc_table = .{
        .success = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ConsoleMessage = struct {
    content: ManagedString = .Empty,
    type: Type = @enumFromInt(0),

    pub const _desc_table = .{
        .content = fd(1, .String),
        .type = fd(2, .{ .Varint = .Simple }),
    };

    pub const Type = enum(i32) {
        TEXT = 0,
        INFO = 1,
        ERROR = 2,
        _,
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const CommandSummary = struct {
    command: ArrayList(Command),

    pub const _desc_table = .{
        .command = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const Command = struct {
    alias: ManagedString = .Empty,
    arguments: ManagedString = .Empty,
    description: ManagedString = .Empty,

    pub const _desc_table = .{
        .alias = fd(1, .String),
        .arguments = fd(2, .String),
        .description = fd(3, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
