// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.alliance.conquest
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
/// import package com.ankama.dofus.server.game.protocol.common
const com_ankama_dofus_server_game_protocol_common = @import("../common.pb.zig");

pub const AVAStateUpdateRequest = struct {
    enable: bool = false,

    pub const _desc_table = .{
        .enable = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AllianceFightListenStartRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AllianceFightListenStopRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AllianceFightJoinRequest = struct {
    fight_information: ?com_ankama_dofus_server_game_protocol_common.SocialFightInformation = null,

    pub const _desc_table = .{
        .fight_information = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AllianceFightReplaceRequest = struct {
    fight_information: ?com_ankama_dofus_server_game_protocol_common.SocialFightInformation = null,
    to_replace_fighter_id: i64 = 0,

    pub const _desc_table = .{
        .fight_information = fd(1, .{ .SubMessage = {} }),
        .to_replace_fighter_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AllianceFightLeaveRequest = struct {
    fight_information: ?com_ankama_dofus_server_game_protocol_common.SocialFightInformation = null,

    pub const _desc_table = .{
        .fight_information = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AllianceFightsInformationEvent = struct {
    alliance_fights: ArrayList(com_ankama_dofus_server_game_protocol_common.SocialFight),

    pub const _desc_table = .{
        .alliance_fights = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AllianceFightStartedEvent = struct {
    fight_information: ?com_ankama_dofus_server_game_protocol_common.SocialFightInformation = null,
    phase: ?com_ankama_dofus_server_game_protocol_common.FightPhaseInfo = null,

    pub const _desc_table = .{
        .fight_information = fd(1, .{ .SubMessage = {} }),
        .phase = fd(2, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AllianceFightFinishedEvent = struct {
    fight_information: ?com_ankama_dofus_server_game_protocol_common.SocialFightInformation = null,

    pub const _desc_table = .{
        .fight_information = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AllianceFightPhaseUpdateEvent = struct {
    fight_information: ?com_ankama_dofus_server_game_protocol_common.SocialFightInformation = null,
    phase: ?com_ankama_dofus_server_game_protocol_common.FightPhaseInfo = null,

    pub const _desc_table = .{
        .fight_information = fd(1, .{ .SubMessage = {} }),
        .phase = fd(2, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AllianceFightFighterAddedEvent = struct {
    fight_information: ?com_ankama_dofus_server_game_protocol_common.SocialFightInformation = null,
    fighter: ?com_ankama_dofus_server_game_protocol_common.Character = null,
    team: com_ankama_dofus_server_game_protocol_common.Team = @enumFromInt(0),

    pub const _desc_table = .{
        .fight_information = fd(1, .{ .SubMessage = {} }),
        .fighter = fd(2, .{ .SubMessage = {} }),
        .team = fd(3, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AllianceFightFighterRemovedEvent = struct {
    fight_information: ?com_ankama_dofus_server_game_protocol_common.SocialFightInformation = null,
    fighter_id: i64 = 0,

    pub const _desc_table = .{
        .fight_information = fd(1, .{ .SubMessage = {} }),
        .fighter_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const KOTHUpdateEvent = struct {
    koth_alliance_information: ArrayList(KOTHAllianceInformation),
    starting_ava_timestamp: ManagedString = .Empty,
    next_tick_time: i64 = 0,

    pub const _desc_table = .{
        .koth_alliance_information = fd(1, .{ .List = .{ .SubMessage = {} } }),
        .starting_ava_timestamp = fd(2, .String),
        .next_tick_time = fd(3, .{ .Varint = .Simple }),
    };

    pub const KOTHAllianceInformation = struct {
        alliance: ?com_ankama_dofus_server_game_protocol_common.AllianceInformation = null,
        member_count: i64 = 0,
        koth_roles: ArrayList(KOTHAllianceRoleNumber),
        scores: ArrayList(KOTHScore),
        match_domination_scores: i32 = 0,

        pub const _desc_table = .{
            .alliance = fd(1, .{ .SubMessage = {} }),
            .member_count = fd(2, .{ .Varint = .Simple }),
            .koth_roles = fd(3, .{ .List = .{ .SubMessage = {} } }),
            .scores = fd(4, .{ .List = .{ .SubMessage = {} } }),
            .match_domination_scores = fd(5, .{ .Varint = .Simple }),
        };

        pub const KOTHAllianceRoleNumber = struct {
            member_count: i64 = 0,
            koth_role: i32 = 0,

            pub const _desc_table = .{
                .member_count = fd(1, .{ .Varint = .Simple }),
                .koth_role = fd(2, .{ .Varint = .Simple }),
            };

            pub usingnamespace protobuf.MessageMixins(@This());
        };

        pub const KOTHScore = struct {
            score_type: KOTHScoreType = @enumFromInt(0),
            round_scores: i32 = 0,
            cumulated_scores: i32 = 0,

            pub const _desc_table = .{
                .score_type = fd(1, .{ .Varint = .Simple }),
                .round_scores = fd(2, .{ .Varint = .Simple }),
                .cumulated_scores = fd(3, .{ .Varint = .Simple }),
            };

            pub const KOTHScoreType = enum(i32) {
                FIGHT = 0,
                DOMINATION = 1,
                PRISM = 2,
                _,
            };

            pub usingnamespace protobuf.MessageMixins(@This());
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const KOTHEndEvent = struct {
    winner: ?com_ankama_dofus_server_game_protocol_common.AllianceInformation = null,

    pub const _desc_table = .{
        .winner = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const NuggetsBeneficiary = struct {
    character_id: i64 = 0,
    nuggets_quantity: i32 = 0,

    pub const _desc_table = .{
        .character_id = fd(1, .{ .Varint = .Simple }),
        .nuggets_quantity = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const NuggetsDistributionRequest = struct {
    beneficiaries: ArrayList(NuggetsBeneficiary),

    pub const _desc_table = .{
        .beneficiaries = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const NuggetsListenStartRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const NuggetsListenStopRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const NuggetsInformationEvent = struct {
    nuggets_quantity: i32 = 0,

    pub const _desc_table = .{
        .nuggets_quantity = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
