// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.alliance.member
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
/// import package com.ankama.dofus.server.game.protocol.common
const com_ankama_dofus_server_game_protocol_common = @import("../common.pb.zig");

pub const AllianceInvitationRequest = struct {
    character_id: i64 = 0,

    pub const _desc_table = .{
        .character_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AllianceInvitationAnswerRequest = struct {
    accepted: bool = false,

    pub const _desc_table = .{
        .accepted = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AllianceKickRequest = struct {
    kicked_id: i64 = 0,

    pub const _desc_table = .{
        .kicked_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AllianceInvitedEvent = struct {
    recruiter_name: ManagedString = .Empty,
    alliance_information: ?com_ankama_dofus_server_game_protocol_common.AllianceInformation = null,

    pub const _desc_table = .{
        .recruiter_name = fd(1, .String),
        .alliance_information = fd(2, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AllianceInvitationStateRecruiterEvent = struct {
    recruited_name: ManagedString = .Empty,
    invitation_state: com_ankama_dofus_server_game_protocol_common.SocialGroupInvitationState = @enumFromInt(0),

    pub const _desc_table = .{
        .recruited_name = fd(1, .String),
        .invitation_state = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AllianceInvitationStateRecruitedEvent = struct {
    invitation_state: com_ankama_dofus_server_game_protocol_common.SocialGroupInvitationState = @enumFromInt(0),

    pub const _desc_table = .{
        .invitation_state = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AllianceMembershipEvent = struct {
    alliance_information: ?com_ankama_dofus_server_game_protocol_common.AllianceInformation = null,
    rank_id: i32 = 0,

    pub const _desc_table = .{
        .alliance_information = fd(1, .{ .SubMessage = {} }),
        .rank_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AllianceJoinedEvent = struct {
    alliance_information: ?com_ankama_dofus_server_game_protocol_common.AllianceInformation = null,
    rank_id: i32 = 0,

    pub const _desc_table = .{
        .alliance_information = fd(1, .{ .SubMessage = {} }),
        .rank_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AllianceMemberLeavingEvent = struct {
    kicked: bool = false,
    member_id: i64 = 0,

    pub const _desc_table = .{
        .kicked = fd(1, .{ .Varint = .Simple }),
        .member_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AllianceLeftEvent = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AllianceMemberUpdateEvent = struct {
    member: ?com_ankama_dofus_server_game_protocol_common.AllianceMemberInformation = null,

    pub const _desc_table = .{
        .member = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
