// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.alliance.rank
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
/// import package com.ankama.dofus.server.game.protocol.common
const com_ankama_dofus_server_game_protocol_common = @import("../common.pb.zig");

pub const AllianceRankCreationRequest = struct {
    parent_rank_id: i32 = 0,
    gfx_id: i32 = 0,
    name: ManagedString = .Empty,

    pub const _desc_table = .{
        .parent_rank_id = fd(1, .{ .Varint = .Simple }),
        .gfx_id = fd(2, .{ .Varint = .Simple }),
        .name = fd(3, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AllianceRankUpdateAllRequest = struct {
    ranks: ArrayList(com_ankama_dofus_server_game_protocol_common.RankInformation),

    pub const _desc_table = .{
        .ranks = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AllianceRankDeletionRequest = struct {
    rank_id: i32 = 0,
    replacement_rank_id: i32 = 0,

    pub const _desc_table = .{
        .rank_id = fd(1, .{ .Varint = .Simple }),
        .replacement_rank_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AllianceRankUpdateRequest = struct {
    rank: ?com_ankama_dofus_server_game_protocol_common.RankInformation = null,

    pub const _desc_table = .{
        .rank = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AllianceRanksRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AllianceRankChangeRequest = struct {
    member_id: i64 = 0,
    rank_id: i32 = 0,

    pub const _desc_table = .{
        .member_id = fd(1, .{ .Varint = .Simple }),
        .rank_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AllianceRanksEvent = struct {
    ranks: ArrayList(com_ankama_dofus_server_game_protocol_common.RankInformation),

    pub const _desc_table = .{
        .ranks = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AllianceRightsUpdateRequest = struct {
    rank_id: i32 = 0,
    rights: ArrayList(i32),

    pub const _desc_table = .{
        .rank_id = fd(1, .{ .Varint = .Simple }),
        .rights = fd(2, .{ .PackedList = .{ .Varint = .Simple } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
