// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.tag.storage
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;

pub const AddTagStorageRequest = struct {
    name: ManagedString = .Empty,
    picto: i32 = 0,

    pub const _desc_table = .{
        .name = fd(1, .String),
        .picto = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AddTagStorageResponse = struct {
    tag_storage_uuid: ManagedString = .Empty,

    pub const _desc_table = .{
        .tag_storage_uuid = fd(1, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const RemoveTagStorageRequest = struct {
    tag_storage_uuid: ManagedString = .Empty,

    pub const _desc_table = .{
        .tag_storage_uuid = fd(1, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const RemoveTagStorageResponse = struct {
    tag_storage_uuid: ManagedString = .Empty,

    pub const _desc_table = .{
        .tag_storage_uuid = fd(1, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AddTagObjectRequest = struct {
    tag_object_update_content: ArrayList(TagObjectUpdateContent),

    pub const _desc_table = .{
        .tag_object_update_content = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AddTagObjectResponse = struct {
    object_ids: ArrayList(i32),

    pub const _desc_table = .{
        .object_ids = fd(1, .{ .PackedList = .{ .Varint = .Simple } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const RemoveTagObjectRequest = struct {
    tag_object_update_content: ArrayList(TagObjectUpdateContent),

    pub const _desc_table = .{
        .tag_object_update_content = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const RemoveTagObjectResponse = struct {
    object_ids: ArrayList(i32),

    pub const _desc_table = .{
        .object_ids = fd(1, .{ .PackedList = .{ .Varint = .Simple } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TagObjectUpdateContent = struct {
    tag_storage_uuid: ManagedString = .Empty,
    object_id: i32 = 0,

    pub const _desc_table = .{
        .tag_storage_uuid = fd(1, .String),
        .object_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const UpdateTagStorageContentRequest = struct {
    tag_storage_data: ?TagStorageData = null,

    pub const _desc_table = .{
        .tag_storage_data = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const UpdateTagStorageContentResponse = struct {
    tag_storage_uuid: ManagedString = .Empty,

    pub const _desc_table = .{
        .tag_storage_uuid = fd(1, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TagStoragesRefreshEvent = struct {
    tag_information: ArrayList(TagInformation),

    pub const _desc_table = .{
        .tag_information = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TagInformation = struct {
    tag_storage_data: ?TagStorageData = null,
    tag_object_data: ?TagObjectData = null,

    pub const _desc_table = .{
        .tag_storage_data = fd(1, .{ .SubMessage = {} }),
        .tag_object_data = fd(2, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TagStorageData = struct {
    tag_storage_uuid: ManagedString = .Empty,
    name: ManagedString = .Empty,
    picto: i32 = 0,

    pub const _desc_table = .{
        .tag_storage_uuid = fd(1, .String),
        .name = fd(2, .String),
        .picto = fd(3, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TagObjectData = struct {
    tag_object_uuids: ArrayList(i32),

    pub const _desc_table = .{
        .tag_object_uuids = fd(1, .{ .PackedList = .{ .Varint = .Simple } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
