// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
/// import package google.protobuf
const google_protobuf = @import("../../../../../google/protobuf.pb.zig");

pub const GameMessage = struct {
    content: ?content_union,

    pub const _content_case = enum {
        request,
        response,
        event,
    };
    pub const content_union = union(_content_case) {
        request: Request,
        response: Response,
        event: Event,
        pub const _union_desc = .{
            .request = fd(1, .{ .SubMessage = {} }),
            .response = fd(2, .{ .SubMessage = {} }),
            .event = fd(3, .{ .SubMessage = {} }),
        };
    };

    pub const _desc_table = .{
        .content = fd(null, .{ .OneOf = content_union }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const Request = struct {
    uid: i32 = 0,
    content: ?google_protobuf.Any = null,

    pub const _desc_table = .{
        .uid = fd(1, .{ .Varint = .Simple }),
        .content = fd(2, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const Response = struct {
    uid: i32 = 0,
    content: ?google_protobuf.Any = null,

    pub const _desc_table = .{
        .uid = fd(1, .{ .Varint = .Simple }),
        .content = fd(2, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const Event = struct {
    content: ?google_protobuf.Any = null,

    pub const _desc_table = .{
        .content = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
