// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.living.object
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;

pub const LivingObjectMessageRequest = struct {
    message_id: i32 = 0,
    object_gid: i32 = 0,

    pub const _desc_table = .{
        .message_id = fd(1, .{ .Varint = .Simple }),
        .object_gid = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const LivingObjectDissociateRequest = struct {
    object_uid: i32 = 0,
    position: i32 = 0,

    pub const _desc_table = .{
        .object_uid = fd(1, .{ .Varint = .Simple }),
        .position = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const LivingObjectChangeSkinRequest = struct {
    object_uid: i32 = 0,
    position: i32 = 0,
    skin_id: i32 = 0,

    pub const _desc_table = .{
        .object_uid = fd(1, .{ .Varint = .Simple }),
        .position = fd(2, .{ .Varint = .Simple }),
        .skin_id = fd(3, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const LivingObjectMessageEvent = struct {
    message_id: i32 = 0,
    timestamp: i64 = 0,
    owner_name: ManagedString = .Empty,
    object_gid: i32 = 0,

    pub const _desc_table = .{
        .message_id = fd(1, .{ .Varint = .Simple }),
        .timestamp = fd(2, .{ .Varint = .Simple }),
        .owner_name = fd(3, .String),
        .object_gid = fd(4, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
