// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.alteration
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
/// import package com.ankama.dofus.server.game.protocol.common
const com_ankama_dofus_server_game_protocol_common = @import("common.pb.zig");

pub const AlterationsEvent = struct {
    alterations: ArrayList(Alteration),

    pub const _desc_table = .{
        .alterations = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AlterationAddedEvent = struct {
    alteration: ?Alteration = null,

    pub const _desc_table = .{
        .alteration = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AlterationRemovedEvent = struct {
    alteration: ?Alteration = null,

    pub const _desc_table = .{
        .alteration = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AlterationsUpdateEvent = struct {
    alterations: ArrayList(Alteration),

    pub const _desc_table = .{
        .alterations = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const Alteration = struct {
    alteration_id: i64 = 0,
    creation_time: i64 = 0,
    expiration_type: AlterationExpirationType = @enumFromInt(0),
    expiration_value: i64 = 0,
    effects: ArrayList(com_ankama_dofus_server_game_protocol_common.ObjectEffect),

    pub const _desc_table = .{
        .alteration_id = fd(1, .{ .Varint = .Simple }),
        .creation_time = fd(2, .{ .Varint = .Simple }),
        .expiration_type = fd(3, .{ .Varint = .Simple }),
        .expiration_value = fd(4, .{ .Varint = .Simple }),
        .effects = fd(5, .{ .List = .{ .SubMessage = {} } }),
    };

    pub const AlterationExpirationType = enum(i32) {
        UNKNOWN = 0,
        INFINITE = 1,
        DATE = 2,
        FIGHT_COUNT = 3,
        FIGHTS_WON_COUNT = 4,
        FIGHTS_LOST_COUNT = 5,
        _,
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
