// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.anomaly
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;

pub const AnomalySubareaInformationRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AnomalySubareaInformationEvent = struct {
    subareas: ArrayList(AnomalySubareaInformation),

    pub const _desc_table = .{
        .subareas = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub const AnomalySubareaInformation = struct {
        subarea_id: i32 = 0,
        reward_rate: i32 = 0,
        has_anomaly: bool = false,
        anomaly_closing_time: i64 = 0,

        pub const _desc_table = .{
            .subarea_id = fd(1, .{ .Varint = .Simple }),
            .reward_rate = fd(2, .{ .Varint = .Simple }),
            .has_anomaly = fd(3, .{ .Varint = .Simple }),
            .anomaly_closing_time = fd(4, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AnomalyStateEvent = struct {
    subarea_id: i32 = 0,
    open: bool = false,
    closing_time: i64 = 0,

    pub const _desc_table = .{
        .subarea_id = fd(1, .{ .Varint = .Simple }),
        .open = fd(2, .{ .Varint = .Simple }),
        .closing_time = fd(3, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AnomalyOpenedEvent = struct {
    subarea_id: i32 = 0,

    pub const _desc_table = .{
        .subarea_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
