// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.breach
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
/// import package com.ankama.dofus.server.game.protocol.common
const com_ankama_dofus_server_game_protocol_common = @import("common.pb.zig");

pub const BreachTeleportRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const BreachRoomUnlockRequest = struct {
    room_id: i32 = 0,

    pub const _desc_table = .{
        .room_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const BreachExitRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const BreachRewardBuyRequest = struct {
    reward_id: i32 = 0,

    pub const _desc_table = .{
        .reward_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const BreachInvitationRequest = struct {
    guests: ArrayList(i64),

    pub const _desc_table = .{
        .guests = fd(1, .{ .PackedList = .{ .Varint = .Simple } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const BreachInvitationAnswerRequest = struct {
    accepted: bool = false,

    pub const _desc_table = .{
        .accepted = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const BreachKickRequest = struct {
    player_id: i64 = 0,

    pub const _desc_table = .{
        .player_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const BreachEnterEvent = struct {
    owner: i64 = 0,

    pub const _desc_table = .{
        .owner = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const BreachTeleportResultEvent = struct {
    teleported: bool = false,

    pub const _desc_table = .{
        .teleported = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const BreachRoomLockedEvent = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const BreachRoomUnlockResultEvent = struct {
    room_id: i32 = 0,
    result: BreachRoomUnlockResult = @enumFromInt(0),

    pub const _desc_table = .{
        .room_id = fd(1, .{ .Varint = .Simple }),
        .result = fd(2, .{ .Varint = .Simple }),
    };

    pub const BreachRoomUnlockResult = enum(i32) {
        SUCCESS = 0,
        FAIL_NOT_ENOUGH_BUDGET = 1,
        _,
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const BreachExitResultEvent = struct {
    exited: bool = false,

    pub const _desc_table = .{
        .exited = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const BreachStateEvent = struct {
    owner: ?com_ankama_dofus_server_game_protocol_common.Character = null,
    bonuses: ArrayList(com_ankama_dofus_server_game_protocol_common.ObjectEffect),
    budget: i32 = 0,
    saved: bool = false,

    pub const _desc_table = .{
        .owner = fd(1, .{ .SubMessage = {} }),
        .bonuses = fd(2, .{ .List = .{ .SubMessage = {} } }),
        .budget = fd(3, .{ .Varint = .Simple }),
        .saved = fd(4, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const BreachCharactersEvent = struct {
    players: ArrayList(i64),

    pub const _desc_table = .{
        .players = fd(1, .{ .PackedList = .{ .Varint = .Simple } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const BreachBonusEvent = struct {
    bonus: ?com_ankama_dofus_server_game_protocol_common.ObjectEffect = null,

    pub const _desc_table = .{
        .bonus = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const BreachBudgetEvent = struct {
    budget: i32 = 0,

    pub const _desc_table = .{
        .budget = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const BreachSavedEvent = struct {
    saved: bool = false,

    pub const _desc_table = .{
        .saved = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const BreachBranchesEvent = struct {
    branches: ArrayList(com_ankama_dofus_server_game_protocol_common.BreachBranch),

    pub const _desc_table = .{
        .branches = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const BreachRewardsEvent = struct {
    rewards: ArrayList(com_ankama_dofus_server_game_protocol_common.BreachReward),

    pub const _desc_table = .{
        .rewards = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const BreachRewardBoughtEvent = struct {
    reward_id: i32 = 0,
    bought: bool = false,

    pub const _desc_table = .{
        .reward_id = fd(1, .{ .Varint = .Simple }),
        .bought = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const BreachInvitationOfferEvent = struct {
    host: ?com_ankama_dofus_server_game_protocol_common.Character = null,
    time_left_before_cancel: i32 = 0,

    pub const _desc_table = .{
        .host = fd(1, .{ .SubMessage = {} }),
        .time_left_before_cancel = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const BreachInvitationCloseEvent = struct {
    host: ?com_ankama_dofus_server_game_protocol_common.Character = null,

    pub const _desc_table = .{
        .host = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
