// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.character
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
/// import package com.ankama.dofus.server.game.protocol.common
const com_ankama_dofus_server_game_protocol_common = @import("common.pb.zig");

pub const PlayerStatusUpdateRequest = struct {
    status: ?com_ankama_dofus_server_game_protocol_common.CharacterStatus = null,

    pub const _desc_table = .{
        .status = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ResetCharacterCharacteristicsRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const FreeSoulRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const CharacterCharacteristicUpgradeRequest = struct {
    strength: i32 = 0,
    vitality: i32 = 0,
    wisdom: i32 = 0,
    chance: i32 = 0,
    agility: i32 = 0,
    intelligence: i32 = 0,

    pub const _desc_table = .{
        .strength = fd(1, .{ .Varint = .Simple }),
        .vitality = fd(2, .{ .Varint = .Simple }),
        .wisdom = fd(3, .{ .Varint = .Simple }),
        .chance = fd(4, .{ .Varint = .Simple }),
        .agility = fd(5, .{ .Varint = .Simple }),
        .intelligence = fd(6, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PlayerStatusUpdateErrorEvent = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PlayerStatusUpdatedEvent = struct {
    account_id: i32 = 0,
    player_id: i64 = 0,
    status: ?com_ankama_dofus_server_game_protocol_common.CharacterStatus = null,

    pub const _desc_table = .{
        .account_id = fd(1, .{ .Varint = .Simple }),
        .player_id = fd(2, .{ .Varint = .Simple }),
        .status = fd(3, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const CharacterCharacteristicsEvent = struct {
    stats: ?com_ankama_dofus_server_game_protocol_common.CharacterCharacteristics = null,

    pub const _desc_table = .{
        .stats = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const CharacterLevelUpEvent = struct {
    new_level: i32 = 0,

    pub const _desc_table = .{
        .new_level = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const CharacterExperienceGainEvent = struct {
    character_experience: i64 = 0,
    mount_experience: i64 = 0,
    guild_experience: i64 = 0,

    pub const _desc_table = .{
        .character_experience = fd(1, .{ .Varint = .Simple }),
        .mount_experience = fd(2, .{ .Varint = .Simple }),
        .guild_experience = fd(3, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const LifePointsRegenBeginEvent = struct {
    regen_rate: i32 = 0,

    pub const _desc_table = .{
        .regen_rate = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const UpdateLifePointsEvent = struct {
    life_points: i32 = 0,
    max_life_points: i32 = 0,
    life_points_gained: ?i32 = null,

    pub const _desc_table = .{
        .life_points = fd(1, .{ .Varint = .Simple }),
        .max_life_points = fd(2, .{ .Varint = .Simple }),
        .life_points_gained = fd(3, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const CharacterLifeStatusEvent = struct {
    state: LifeStatus = @enumFromInt(0),
    phoenix_map_id: i64 = 0,

    pub const _desc_table = .{
        .state = fd(1, .{ .Varint = .Simple }),
        .phoenix_map_id = fd(2, .{ .Varint = .Simple }),
    };

    pub const LifeStatus = enum(i32) {
        ALIVE_AND_KICKING = 0,
        TOMBSTONE = 1,
        PHANTOM = 2,
        _,
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const GameOverEvent = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const CharacterCharacteristicUpgradeResultEvent = struct {
    result: CharacteristicUpgradeResult = @enumFromInt(0),
    points: i32 = 0,

    pub const _desc_table = .{
        .result = fd(1, .{ .Varint = .Simple }),
        .points = fd(2, .{ .Varint = .Simple }),
    };

    pub const CharacteristicUpgradeResult = enum(i32) {
        NONE = 0,
        SUCCESS = 1,
        GUEST = 2,
        IN_FIGHT = 3,
        NOT_ENOUGH_POINT = 4,
        _,
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const CharacterRestrictionsEvent = struct {
    character_id: i64 = 0,
    restrictions: ArrayList(com_ankama_dofus_server_game_protocol_common.Restriction),

    pub const _desc_table = .{
        .character_id = fd(1, .{ .Varint = .Simple }),
        .restrictions = fd(2, .{ .List = .{ .Varint = .Simple } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const CharacterOnConnectionEvent = struct {
    connection_event: ConnectionEvent = @enumFromInt(0),

    pub const _desc_table = .{
        .connection_event = fd(1, .{ .Varint = .Simple }),
    };

    pub const ConnectionEvent = enum(i32) {
        FIRST_ACCOUNT_CONNECTION_EVER = 0,
        FIRST_ACCOUNT_CONNECTION_ON_SERVER = 1,
        FIRST_ACCOUNT_CONNECTION_SINCE_REBOOT = 2,
        FIRST_CHARACTER_CONNECTION = 3,
        FIRST_CHARACTER_CONNECTION_SINCE_REBOOT = 4,
        _,
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
