// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.debt
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;

pub const DebtsUpdateEvent = struct {
    action: DebtsAction = @enumFromInt(0),
    debts: ArrayList(DebtInformation),

    pub const _desc_table = .{
        .action = fd(1, .{ .Varint = .Simple }),
        .debts = fd(2, .{ .List = .{ .SubMessage = {} } }),
    };

    pub const DebtsAction = enum(i32) {
        DISPATCH = 0,
        UPDATE = 1,
        _,
    };

    pub const DebtInformation = struct {
        debt_id: i64 = 0,
        timestamp: i64 = 0,
        kamas: ?i64 = null,

        pub const _desc_table = .{
            .debt_id = fd(1, .{ .Varint = .Simple }),
            .timestamp = fd(2, .{ .Varint = .Simple }),
            .kamas = fd(3, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const DebtsDeleteEvent = struct {
    reason: DebtsDeletionReason = @enumFromInt(0),
    debts: ArrayList(i64),

    pub const _desc_table = .{
        .reason = fd(1, .{ .Varint = .Simple }),
        .debts = fd(2, .{ .PackedList = .{ .Varint = .Simple } }),
    };

    pub const DebtsDeletionReason = enum(i32) {
        UNKNOWN = 0,
        ADMIN_COMMAND_REQUEST = 1,
        PAYED = 2,
        CANCELED = 3,
        _,
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
