// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.debug
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
/// import package com.ankama.dofus.server.game.protocol.common
const com_ankama_dofus_server_game_protocol_common = @import("common.pb.zig");

pub const DumpedEntityStatsEvent = struct {
    entity_id: i64 = 0,
    stats: ArrayList(com_ankama_dofus_server_game_protocol_common.CharacterCharacteristic),

    pub const _desc_table = .{
        .entity_id = fd(1, .{ .Varint = .Simple }),
        .stats = fd(2, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const DebugHighlightCellsEvent = struct {
    color: i64 = 0,
    cells: ArrayList(i32),

    pub const _desc_table = .{
        .color = fd(1, .{ .Varint = .Simple }),
        .cells = fd(2, .{ .PackedList = .{ .Varint = .Simple } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const DebugClearHighlightCellsEvent = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const DebugInClientEvent = struct {
    level: DebugLevel = @enumFromInt(0),
    message: ManagedString = .Empty,

    pub const _desc_table = .{
        .level = fd(1, .{ .Varint = .Simple }),
        .message = fd(2, .String),
    };

    pub const DebugLevel = enum(i32) {
        TRACE = 0,
        DEBUG = 1,
        INFO = 2,
        WARN = 3,
        ERROR = 4,
        FATAL = 5,
        _,
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
