// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.dialog
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
/// import package com.ankama.dofus.server.game.protocol.common
const com_ankama_dofus_server_game_protocol_common = @import("common.pb.zig");

pub const DialogLeaveRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const DialogLeaveEvent = struct {
    dialog_type: com_ankama_dofus_server_game_protocol_common.DialogType = @enumFromInt(0),

    pub const _desc_table = .{
        .dialog_type = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ChangeAppearanceDialogStart = struct {
    type: AppearanceType = @enumFromInt(0),

    pub const _desc_table = .{
        .type = fd(1, .{ .Varint = .Simple }),
    };

    pub const AppearanceType = enum(i32) {
        BODY = 0,
        FACE = 1,
        COLORS = 2,
        _,
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ChangeAppearanceDialogLeave = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ChangeAppearanceDialogResult = struct {
    success: bool = false,

    pub const _desc_table = .{
        .success = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
