// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.document
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;

pub const DocumentReadingBeginEvent = struct {
    document_id: i32 = 0,

    pub const _desc_table = .{
        .document_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const OpenGuideBookEvent = struct {
    article_id: i32 = 0,

    pub const _desc_table = .{
        .article_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
