// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.emote
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;

pub const EmotePlayRequest = struct {
    emote_id: i32 = 0,
    only_play_emote: bool = false,

    pub const _desc_table = .{
        .emote_id = fd(1, .{ .Varint = .Simple }),
        .only_play_emote = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const EmotesEvent = struct {
    emotes_id: ArrayList(i32),

    pub const _desc_table = .{
        .emotes_id = fd(1, .{ .PackedList = .{ .Varint = .Simple } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const EmoteAddedEvent = struct {
    emote_id: i32 = 0,

    pub const _desc_table = .{
        .emote_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const EmoteRemovedEvent = struct {
    emote_id: i32 = 0,

    pub const _desc_table = .{
        .emote_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const EmotePlayEvent = struct {
    emote_id: i32 = 0,
    emote_start_time: i64 = 0,
    actor_id: i64 = 0,
    account_id: i32 = 0,

    pub const _desc_table = .{
        .emote_id = fd(1, .{ .Varint = .Simple }),
        .emote_start_time = fd(2, .{ .Varint = .Simple }),
        .actor_id = fd(3, .{ .Varint = .Simple }),
        .account_id = fd(4, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const EmoteMassivePlayEvent = struct {
    emote_id: i32 = 0,
    emote_start_time: i64 = 0,
    actors_id: ArrayList(i64),

    pub const _desc_table = .{
        .emote_id = fd(1, .{ .Varint = .Simple }),
        .emote_start_time = fd(2, .{ .Varint = .Simple }),
        .actors_id = fd(3, .{ .PackedList = .{ .Varint = .Simple } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const EmotePlayErrorEvent = struct {
    emote_id: i32 = 0,

    pub const _desc_table = .{
        .emote_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
