// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.haapi
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;

pub const HaapiTokenRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const HaapiTokenEvent = struct {
    token: ManagedString = .Empty,

    pub const _desc_table = .{
        .token = fd(1, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const HaapiAuthenticationErrorEvent = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const HaapiSessionEvent = struct {
    session_uid: ManagedString = .Empty,

    pub const _desc_table = .{
        .session_uid = fd(1, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
