// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.house
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
/// import package com.ankama.dofus.server.game.protocol.common
const com_ankama_dofus_server_game_protocol_common = @import("common.pb.zig");

pub const HouseInformationRequest = struct {
    house_id: i32 = 0,
    house_instance_id: i64 = 0,

    pub const _desc_table = .{
        .house_id = fd(1, .{ .Varint = .Simple }),
        .house_instance_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const HouseInformationResponse = struct {
    house_information: ?com_ankama_dofus_server_game_protocol_common.HouseInstance = null,

    pub const _desc_table = .{
        .house_information = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const HouseKickRequest = struct {
    player_id: i64 = 0,

    pub const _desc_table = .{
        .player_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const HouseSellRequest = struct {
    instance_id: i32 = 0,
    amount: i64 = 0,
    for_sale: bool = false,
    is_inside: bool = false,

    pub const _desc_table = .{
        .instance_id = fd(1, .{ .Varint = .Simple }),
        .amount = fd(2, .{ .Varint = .Simple }),
        .for_sale = fd(3, .{ .Varint = .Simple }),
        .is_inside = fd(4, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const HouseBuyRequest = struct {
    proposed_price: i64 = 0,

    pub const _desc_table = .{
        .proposed_price = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const HouseLockFromInsideRequest = struct {
    code: ManagedString = .Empty,

    pub const _desc_table = .{
        .code = fd(1, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const HousesToSellRequest = struct {
    page_index: i32 = 0,

    pub const _desc_table = .{
        .page_index = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const HousesToSellFiltersRequest = struct {
    area_id: i32 = 0,
    at_least_room_number: i32 = 0,
    at_least_chest_number: i32 = 0,
    skill_requested: i32 = 0,
    price_max: i64 = 0,
    order_by: com_ankama_dofus_server_game_protocol_common.RealEstateOrder = @enumFromInt(0),

    pub const _desc_table = .{
        .area_id = fd(1, .{ .Varint = .Simple }),
        .at_least_room_number = fd(2, .{ .Varint = .Simple }),
        .at_least_chest_number = fd(3, .{ .Varint = .Simple }),
        .skill_requested = fd(4, .{ .Varint = .Simple }),
        .price_max = fd(5, .{ .Varint = .Simple }),
        .order_by = fd(6, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const HouseTeleportRequest = struct {
    house_id: i32 = 0,
    instance_id: i32 = 0,

    pub const _desc_table = .{
        .house_id = fd(1, .{ .Varint = .Simple }),
        .instance_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const HouseGuildRightsViewRequest = struct {
    house_id: i32 = 0,
    instance_id: i32 = 0,

    pub const _desc_table = .{
        .house_id = fd(1, .{ .Varint = .Simple }),
        .instance_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const HouseGuildShareRequest = struct {
    house_id: i32 = 0,
    instance_id: i32 = 0,
    share: bool = false,
    rights: i32 = 0,

    pub const _desc_table = .{
        .house_id = fd(1, .{ .Varint = .Simple }),
        .instance_id = fd(2, .{ .Varint = .Simple }),
        .share = fd(3, .{ .Varint = .Simple }),
        .rights = fd(4, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const HouseAccountEvent = struct {
    houses: ArrayList(com_ankama_dofus_server_game_protocol_common.House),

    pub const _desc_table = .{
        .houses = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const HousePropertiesEvent = struct {
    house_id: i32 = 0,
    doors_on_map: ArrayList(i32),
    properties: ?com_ankama_dofus_server_game_protocol_common.HouseInstance = null,

    pub const _desc_table = .{
        .house_id = fd(1, .{ .Varint = .Simple }),
        .doors_on_map = fd(2, .{ .PackedList = .{ .Varint = .Simple } }),
        .properties = fd(3, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const HouseBuyResultEvent = struct {
    house_id: i32 = 0,
    instance_id: i32 = 0,
    second_hand: bool = false,
    bought: bool = false,
    price: i64 = 0,

    pub const _desc_table = .{
        .house_id = fd(1, .{ .Varint = .Simple }),
        .instance_id = fd(2, .{ .Varint = .Simple }),
        .second_hand = fd(3, .{ .Varint = .Simple }),
        .bought = fd(4, .{ .Varint = .Simple }),
        .price = fd(5, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const HouseSellingUpdateEvent = struct {
    house_id: i32 = 0,
    instance_id: i32 = 0,
    second_hand: bool = false,
    price: i64 = 0,
    buyer_account_nickname: ManagedString = .Empty,
    buyer_account_tag: ManagedString = .Empty,

    pub const _desc_table = .{
        .house_id = fd(1, .{ .Varint = .Simple }),
        .instance_id = fd(2, .{ .Varint = .Simple }),
        .second_hand = fd(3, .{ .Varint = .Simple }),
        .price = fd(4, .{ .Varint = .Simple }),
        .buyer_account_nickname = fd(5, .String),
        .buyer_account_tag = fd(6, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const HousesToSellEvent = struct {
    page_index: i32 = 0,
    total_page: i32 = 0,
    houses: ArrayList(HouseToSell),

    pub const _desc_table = .{
        .page_index = fd(1, .{ .Varint = .Simple }),
        .total_page = fd(2, .{ .Varint = .Simple }),
        .houses = fd(3, .{ .List = .{ .SubMessage = {} } }),
    };

    pub const HouseToSell = struct {
        instance_id: i32 = 0,
        second_hand: bool = false,
        model_id: i32 = 0,
        owner_account_nickname: ManagedString = .Empty,
        owner_account_tag: ManagedString = .Empty,
        has_owner: bool = false,
        owner_name: ManagedString = .Empty,
        coordinates: ?com_ankama_dofus_server_game_protocol_common.MapCoordinates = null,
        sub_area_id: i32 = 0,
        room_number: i32 = 0,
        chest_number: i32 = 0,
        skills_id: ArrayList(i32),
        is_locked: bool = false,
        price: i64 = 0,

        pub const _desc_table = .{
            .instance_id = fd(1, .{ .Varint = .Simple }),
            .second_hand = fd(2, .{ .Varint = .Simple }),
            .model_id = fd(3, .{ .Varint = .Simple }),
            .owner_account_nickname = fd(4, .String),
            .owner_account_tag = fd(5, .String),
            .has_owner = fd(6, .{ .Varint = .Simple }),
            .owner_name = fd(7, .String),
            .coordinates = fd(8, .{ .SubMessage = {} }),
            .sub_area_id = fd(9, .{ .Varint = .Simple }),
            .room_number = fd(10, .{ .Varint = .Simple }),
            .chest_number = fd(11, .{ .Varint = .Simple }),
            .skills_id = fd(12, .{ .PackedList = .{ .Varint = .Simple } }),
            .is_locked = fd(13, .{ .Varint = .Simple }),
            .price = fd(14, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const HouseGuildNoneEvent = struct {
    house_id: i32 = 0,
    instance_id: i32 = 0,
    second_hand: bool = false,

    pub const _desc_table = .{
        .house_id = fd(1, .{ .Varint = .Simple }),
        .instance_id = fd(2, .{ .Varint = .Simple }),
        .second_hand = fd(3, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const HouseGuildRightsEvent = struct {
    house_id: i32 = 0,
    instance_id: i32 = 0,
    second_hand: bool = false,
    guild_information: ?com_ankama_dofus_server_game_protocol_common.GuildInformation = null,
    rights: i32 = 0,
    is_locked: bool = false,

    pub const _desc_table = .{
        .house_id = fd(1, .{ .Varint = .Simple }),
        .instance_id = fd(2, .{ .Varint = .Simple }),
        .second_hand = fd(3, .{ .Varint = .Simple }),
        .guild_information = fd(4, .{ .SubMessage = {} }),
        .rights = fd(5, .{ .Varint = .Simple }),
        .is_locked = fd(6, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
