// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.inventory
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
/// import package com.ankama.dofus.server.game.protocol.common
const com_ankama_dofus_server_game_protocol_common = @import("common.pb.zig");

pub const ShortcutBarAddRequest = struct {
    bar_type: com_ankama_dofus_server_game_protocol_common.ShortcutBar = @enumFromInt(0),
    shortcut: ?com_ankama_dofus_server_game_protocol_common.Shortcut = null,

    pub const _desc_table = .{
        .bar_type = fd(1, .{ .Varint = .Simple }),
        .shortcut = fd(2, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ShortcutBarRemoveRequest = struct {
    bar_type: com_ankama_dofus_server_game_protocol_common.ShortcutBar = @enumFromInt(0),
    slot_id: i32 = 0,

    pub const _desc_table = .{
        .bar_type = fd(1, .{ .Varint = .Simple }),
        .slot_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ShortcutBarSwapRequest = struct {
    bar_type: com_ankama_dofus_server_game_protocol_common.ShortcutBar = @enumFromInt(0),
    first_slot_id: i32 = 0,
    second_slot_id: i32 = 0,

    pub const _desc_table = .{
        .bar_type = fd(1, .{ .Varint = .Simple }),
        .first_slot_id = fd(2, .{ .Varint = .Simple }),
        .second_slot_id = fd(3, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ObjectSetPositionRequest = struct {
    object_uid: i32 = 0,
    position: i32 = 0,
    quantity: i32 = 0,

    pub const _desc_table = .{
        .object_uid = fd(1, .{ .Varint = .Simple }),
        .position = fd(2, .{ .Varint = .Simple }),
        .quantity = fd(3, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ObjectDropRequest = struct {
    object: ?com_ankama_dofus_server_game_protocol_common.ObjectUidWithQuantity = null,

    pub const _desc_table = .{
        .object = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ObjectDeleteRequest = struct {
    object: ?com_ankama_dofus_server_game_protocol_common.ObjectUidWithQuantity = null,

    pub const _desc_table = .{
        .object = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ObjectUseRequest = struct {
    object_uid: i32 = 0,

    pub const _desc_table = .{
        .object_uid = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ObjectUseMultipleRequest = struct {
    object_uid: i32 = 0,
    quantity: i32 = 0,

    pub const _desc_table = .{
        .object_uid = fd(1, .{ .Varint = .Simple }),
        .quantity = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ObjectUseOnCharacterRequest = struct {
    object_uid: i32 = 0,
    player_id: i64 = 0,

    pub const _desc_table = .{
        .object_uid = fd(1, .{ .Varint = .Simple }),
        .player_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ObjectUseOnCellRequest = struct {
    object_uid: i32 = 0,
    cell_id: i32 = 0,

    pub const _desc_table = .{
        .object_uid = fd(1, .{ .Varint = .Simple }),
        .cell_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ObjectFeedRequest = struct {
    object_uid: i32 = 0,
    meal: ArrayList(com_ankama_dofus_server_game_protocol_common.ObjectUidWithQuantity),

    pub const _desc_table = .{
        .object_uid = fd(1, .{ .Varint = .Simple }),
        .meal = fd(2, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ObjectFavoriteRequest = struct {
    objects: ArrayList(ObjectFavorite),
    favorite: bool = false,

    pub const _desc_table = .{
        .objects = fd(1, .{ .List = .{ .SubMessage = {} } }),
        .favorite = fd(2, .{ .Varint = .Simple }),
    };

    pub const ObjectFavorite = struct {
        object_uid: i32 = 0,
        position: i32 = 0,

        pub const _desc_table = .{
            .object_uid = fd(1, .{ .Varint = .Simple }),
            .position = fd(2, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const KamasUpdateEvent = struct {
    quantity: i64 = 0,

    pub const _desc_table = .{
        .quantity = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ObjectDroppedEvent = struct {
    object: ?com_ankama_dofus_server_game_protocol_common.ObjectInRolePlay = null,

    pub const _desc_table = .{
        .object = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ObjectsDroppedEvent = struct {
    object: ArrayList(com_ankama_dofus_server_game_protocol_common.ObjectInRolePlay),

    pub const _desc_table = .{
        .object = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ObjectCellDeleteEvent = struct {
    cell_id: i32 = 0,

    pub const _desc_table = .{
        .cell_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ObjectCellsDeleteEvent = struct {
    cells_id: ArrayList(i32),

    pub const _desc_table = .{
        .cells_id = fd(1, .{ .PackedList = .{ .Varint = .Simple } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ObjectMovementEvent = struct {
    object_uid: i32 = 0,
    position: i32 = 0,

    pub const _desc_table = .{
        .object_uid = fd(1, .{ .Varint = .Simple }),
        .position = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ObjectAddedEvent = struct {
    object: ?com_ankama_dofus_server_game_protocol_common.ObjectItemInventory = null,
    origin: com_ankama_dofus_server_game_protocol_common.ObjectOrigin = @enumFromInt(0),

    pub const _desc_table = .{
        .object = fd(1, .{ .SubMessage = {} }),
        .origin = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ObjectsAddedEvent = struct {
    objects: ArrayList(com_ankama_dofus_server_game_protocol_common.ObjectItemInventory),

    pub const _desc_table = .{
        .objects = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const GoldAddedEvent = struct {
    sum: i64 = 0,

    pub const _desc_table = .{
        .sum = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ObjectErrorEvent = struct {
    reason: com_ankama_dofus_server_game_protocol_common.ObjectError = @enumFromInt(0),

    pub const _desc_table = .{
        .reason = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ObjectDeletedEvent = struct {
    object_uid: i32 = 0,

    pub const _desc_table = .{
        .object_uid = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ObjectsDeletedEvent = struct {
    objects_uid: ArrayList(i32),

    pub const _desc_table = .{
        .objects_uid = fd(1, .{ .PackedList = .{ .Varint = .Simple } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ObjectQuantityEvent = struct {
    object: ?com_ankama_dofus_server_game_protocol_common.ObjectUidWithQuantity = null,
    origin: com_ankama_dofus_server_game_protocol_common.ObjectOrigin = @enumFromInt(0),

    pub const _desc_table = .{
        .object = fd(1, .{ .SubMessage = {} }),
        .origin = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ObjectsQuantityEvent = struct {
    object: ArrayList(com_ankama_dofus_server_game_protocol_common.ObjectUidWithQuantity),

    pub const _desc_table = .{
        .object = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ObjectModifiedEvent = struct {
    object: ?com_ankama_dofus_server_game_protocol_common.ObjectItemInventory = null,

    pub const _desc_table = .{
        .object = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ObjectFavoriteResponse = struct {
    result: bool = false,

    pub const _desc_table = .{
        .result = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ObjectHarvestedEvent = struct {
    object_gid: i32 = 0,
    quantity: i32 = 0,

    pub const _desc_table = .{
        .object_gid = fd(1, .{ .Varint = .Simple }),
        .quantity = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ObjectHarvestedWithBonusEvent = struct {
    object_gid: i32 = 0,
    quantity: i32 = 0,
    bonus_quantity: i32 = 0,

    pub const _desc_table = .{
        .object_gid = fd(1, .{ .Varint = .Simple }),
        .quantity = fd(2, .{ .Varint = .Simple }),
        .bonus_quantity = fd(3, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const InventoryContentEvent = struct {
    objects: ArrayList(com_ankama_dofus_server_game_protocol_common.ObjectItemInventory),
    kamas: i64 = 0,

    pub const _desc_table = .{
        .objects = fd(1, .{ .List = .{ .SubMessage = {} } }),
        .kamas = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const InventoryContentWatchEvent = struct {
    objects: ArrayList(com_ankama_dofus_server_game_protocol_common.ObjectItemInventory),
    kamas: i64 = 0,

    pub const _desc_table = .{
        .objects = fd(1, .{ .List = .{ .SubMessage = {} } }),
        .kamas = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const InventoryWeightEvent = struct {
    inventory_weight: i32 = 0,
    weight_max: i32 = 0,

    pub const _desc_table = .{
        .inventory_weight = fd(1, .{ .Varint = .Simple }),
        .weight_max = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ShortcutBarContentEvent = struct {
    bar_type: com_ankama_dofus_server_game_protocol_common.ShortcutBar = @enumFromInt(0),
    shortcuts: ArrayList(com_ankama_dofus_server_game_protocol_common.Shortcut),

    pub const _desc_table = .{
        .bar_type = fd(1, .{ .Varint = .Simple }),
        .shortcuts = fd(2, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ShortcutBarRefreshEvent = struct {
    bar_type: com_ankama_dofus_server_game_protocol_common.ShortcutBar = @enumFromInt(0),
    shortcut: ?com_ankama_dofus_server_game_protocol_common.Shortcut = null,

    pub const _desc_table = .{
        .bar_type = fd(1, .{ .Varint = .Simple }),
        .shortcut = fd(2, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ShortcutBarRemovedEvent = struct {
    bar_type: com_ankama_dofus_server_game_protocol_common.ShortcutBar = @enumFromInt(0),
    slot_id: i32 = 0,

    pub const _desc_table = .{
        .bar_type = fd(1, .{ .Varint = .Simple }),
        .slot_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ShortcutBarReplacedEvent = struct {
    bar_type: com_ankama_dofus_server_game_protocol_common.ShortcutBar = @enumFromInt(0),
    shortcut: ?com_ankama_dofus_server_game_protocol_common.Shortcut = null,

    pub const _desc_table = .{
        .bar_type = fd(1, .{ .Varint = .Simple }),
        .shortcut = fd(2, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const StorageTab = struct {
    name: ManagedString = .Empty,
    tab_number: i32 = 0,
    picto: i32 = 0,
    open_right: i32 = 0,
    drop_right: i32 = 0,
    take_right: i32 = 0,
    drop_type_limit: ArrayList(i32),

    pub const _desc_table = .{
        .name = fd(1, .String),
        .tab_number = fd(2, .{ .Varint = .Simple }),
        .picto = fd(3, .{ .Varint = .Simple }),
        .open_right = fd(4, .{ .Varint = .Simple }),
        .drop_right = fd(5, .{ .Varint = .Simple }),
        .take_right = fd(6, .{ .Varint = .Simple }),
        .drop_type_limit = fd(7, .{ .PackedList = .{ .Varint = .Simple } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const MultiTabStorageEvent = struct {
    tabs: ArrayList(StorageTab),

    pub const _desc_table = .{
        .tabs = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const StorageInventoryContentEvent = struct {
    objects: ArrayList(com_ankama_dofus_server_game_protocol_common.ObjectItemInventory),
    kamas: i64 = 0,

    pub const _desc_table = .{
        .objects = fd(1, .{ .List = .{ .SubMessage = {} } }),
        .kamas = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const StorageKamasUpdateEvent = struct {
    kamas: i64 = 0,

    pub const _desc_table = .{
        .kamas = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const StorageObjectUpdateEvent = struct {
    object: ?com_ankama_dofus_server_game_protocol_common.ObjectItemInventory = null,

    pub const _desc_table = .{
        .object = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const StorageObjectsUpdateEvent = struct {
    objects: ArrayList(com_ankama_dofus_server_game_protocol_common.ObjectItemInventory),

    pub const _desc_table = .{
        .objects = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const StorageObjectRemovedEvent = struct {
    object_uid: i32 = 0,

    pub const _desc_table = .{
        .object_uid = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const StorageObjectsRemovedEvent = struct {
    objects_uid: ArrayList(i32),

    pub const _desc_table = .{
        .objects_uid = fd(1, .{ .PackedList = .{ .Varint = .Simple } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const SetUpdateEvent = struct {
    set_id: i32 = 0,
    objects_uid: ArrayList(i32),
    effects: ArrayList(com_ankama_dofus_server_game_protocol_common.ObjectEffect),

    pub const _desc_table = .{
        .set_id = fd(1, .{ .Varint = .Simple }),
        .objects_uid = fd(2, .{ .PackedList = .{ .Varint = .Simple } }),
        .effects = fd(3, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
