// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.job
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
/// import package com.ankama.dofus.server.game.protocol.common
const com_ankama_dofus_server_game_protocol_common = @import("common.pb.zig");

pub const JobCrafterDirectoryListRequest = struct {
    job_id: i32 = 0,

    pub const _desc_table = .{
        .job_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const JobCrafterDirectorySettingsRequest = struct {
    settings: ?JobCrafterDirectorySettings = null,

    pub const _desc_table = .{
        .settings = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const JobDescriptionEvent = struct {
    jobs: ArrayList(JobDescription),

    pub const _desc_table = .{
        .jobs = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const JobLevelUpEvent = struct {
    new_level: i32 = 0,
    job: ?JobDescription = null,

    pub const _desc_table = .{
        .new_level = fd(1, .{ .Varint = .Simple }),
        .job = fd(2, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const JobExperiencesUpdateEvent = struct {
    experiences: ArrayList(JobExperience),

    pub const _desc_table = .{
        .experiences = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const JobExperienceOtherPlayerUpdateEvent = struct {
    experience: ?JobExperience = null,
    player_id: i64 = 0,

    pub const _desc_table = .{
        .experience = fd(1, .{ .SubMessage = {} }),
        .player_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const JobMultiCraftStateEvent = struct {
    enabled: bool = false,
    player_skills: ?PlayerSkills = null,

    pub const _desc_table = .{
        .enabled = fd(1, .{ .Varint = .Simple }),
        .player_skills = fd(2, .{ .SubMessage = {} }),
    };

    pub const PlayerSkills = struct {
        player_id: i64 = 0,
        skills: ArrayList(i32),

        pub const _desc_table = .{
            .player_id = fd(1, .{ .Varint = .Simple }),
            .skills = fd(2, .{ .PackedList = .{ .Varint = .Simple } }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const JobCrafterDirectoryListEvent = struct {
    list_entries: ArrayList(JobCrafterDirectoryEntry),

    pub const _desc_table = .{
        .list_entries = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const JobCrafterDirectorySettingsEvent = struct {
    settings: ArrayList(JobCrafterDirectorySettings),

    pub const _desc_table = .{
        .settings = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const JobBookSubscriptionEvent = struct {
    subscriptions: ArrayList(Subscription),

    pub const _desc_table = .{
        .subscriptions = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub const Subscription = struct {
        job_id: i32 = 0,
        subscribed: bool = false,

        pub const _desc_table = .{
            .job_id = fd(1, .{ .Varint = .Simple }),
            .subscribed = fd(2, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const JobCrafterDirectoryRemoveEvent = struct {
    job_id: i32 = 0,
    player_id: i64 = 0,

    pub const _desc_table = .{
        .job_id = fd(1, .{ .Varint = .Simple }),
        .player_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const JobCrafterDirectoryAddEvent = struct {
    entry: ?JobCrafterDirectoryEntry = null,

    pub const _desc_table = .{
        .entry = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const JobCrafterDirectoryEntryEvent = struct {
    player_information: ?JobCrafterDirectoryPlayerInformation = null,
    jobs_information: ArrayList(JobCrafterDirectoryJobInformation),
    look: ?com_ankama_dofus_server_game_protocol_common.EntityLook = null,

    pub const _desc_table = .{
        .player_information = fd(1, .{ .SubMessage = {} }),
        .jobs_information = fd(2, .{ .List = .{ .SubMessage = {} } }),
        .look = fd(3, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const JobDescription = struct {
    job_id: i32 = 0,
    skills: ArrayList(SkillAction),

    pub const _desc_table = .{
        .job_id = fd(1, .{ .Varint = .Simple }),
        .skills = fd(2, .{ .List = .{ .SubMessage = {} } }),
    };

    pub const SkillAction = struct {
        skill_id: i32 = 0,
        action: ?action_union,

        pub const _action_case = enum {
            timed,
            craft,
        };
        pub const action_union = union(_action_case) {
            timed: Timed,
            craft: Craft,
            pub const _union_desc = .{
                .timed = fd(2, .{ .SubMessage = {} }),
                .craft = fd(3, .{ .SubMessage = {} }),
            };
        };

        pub const _desc_table = .{
            .skill_id = fd(1, .{ .Varint = .Simple }),
            .action = fd(null, .{ .OneOf = action_union }),
        };

        pub const Timed = struct {
            time: i32 = 0,
            collect: ?Collect = null,

            pub const _desc_table = .{
                .time = fd(1, .{ .Varint = .Simple }),
                .collect = fd(2, .{ .SubMessage = {} }),
            };

            pub const Collect = struct {
                min: i32 = 0,
                max: i32 = 0,

                pub const _desc_table = .{
                    .min = fd(1, .{ .Varint = .Simple }),
                    .max = fd(2, .{ .Varint = .Simple }),
                };

                pub usingnamespace protobuf.MessageMixins(@This());
            };

            pub usingnamespace protobuf.MessageMixins(@This());
        };

        pub const Craft = struct {
            probability: i32 = 0,

            pub const _desc_table = .{
                .probability = fd(1, .{ .Varint = .Simple }),
            };

            pub usingnamespace protobuf.MessageMixins(@This());
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const JobExperience = struct {
    job_id: i32 = 0,
    job_level: i32 = 0,
    job_xp: i64 = 0,
    job_xp_level_floor: i64 = 0,
    job_xp_next_level_floor: i64 = 0,

    pub const _desc_table = .{
        .job_id = fd(1, .{ .Varint = .Simple }),
        .job_level = fd(2, .{ .Varint = .Simple }),
        .job_xp = fd(3, .{ .Varint = .Simple }),
        .job_xp_level_floor = fd(4, .{ .Varint = .Simple }),
        .job_xp_next_level_floor = fd(5, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const JobCrafterDirectoryEntry = struct {
    player_information: ?JobCrafterDirectoryPlayerInformation = null,
    job_information: ?JobCrafterDirectoryJobInformation = null,

    pub const _desc_table = .{
        .player_information = fd(1, .{ .SubMessage = {} }),
        .job_information = fd(2, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const JobCrafterDirectoryPlayerInformation = struct {
    player_id: i64 = 0,
    name: ManagedString = .Empty,
    alignment: com_ankama_dofus_server_game_protocol_common.Alignment = @enumFromInt(0),
    breed: i32 = 0,
    gender: com_ankama_dofus_server_game_protocol_common.Gender = @enumFromInt(0),
    is_in_workshop: bool = false,
    coordinates: ?com_ankama_dofus_server_game_protocol_common.MapExtendedCoordinates = null,
    can_craft_legendary: bool = false,
    status: ?com_ankama_dofus_server_game_protocol_common.CharacterStatus = null,

    pub const _desc_table = .{
        .player_id = fd(1, .{ .Varint = .Simple }),
        .name = fd(2, .String),
        .alignment = fd(3, .{ .Varint = .Simple }),
        .breed = fd(4, .{ .Varint = .Simple }),
        .gender = fd(5, .{ .Varint = .Simple }),
        .is_in_workshop = fd(6, .{ .Varint = .Simple }),
        .coordinates = fd(7, .{ .SubMessage = {} }),
        .can_craft_legendary = fd(8, .{ .Varint = .Simple }),
        .status = fd(9, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const JobCrafterDirectoryJobInformation = struct {
    job_id: i32 = 0,
    job_level: i32 = 0,
    free: bool = false,
    min_level: i32 = 0,

    pub const _desc_table = .{
        .job_id = fd(1, .{ .Varint = .Simple }),
        .job_level = fd(2, .{ .Varint = .Simple }),
        .free = fd(3, .{ .Varint = .Simple }),
        .min_level = fd(4, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const JobCrafterDirectorySettings = struct {
    job_id: i32 = 0,
    min_level: i32 = 0,
    free: bool = false,

    pub const _desc_table = .{
        .job_id = fd(1, .{ .Varint = .Simple }),
        .min_level = fd(2, .{ .Varint = .Simple }),
        .free = fd(3, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
