// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.moderation
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;

pub const PopupWarningCloseRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PopupWarningEvent = struct {
    lock_duration: i32 = 0,
    author: ManagedString = .Empty,
    content: ManagedString = .Empty,

    pub const _desc_table = .{
        .lock_duration = fd(1, .{ .Varint = .Simple }),
        .author = fd(2, .String),
        .content = fd(3, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PopupWarningClosedEvent = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};
