// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.mount
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
/// import package com.ankama.dofus.server.game.protocol.common
const com_ankama_dofus_server_game_protocol_common = @import("common.pb.zig");

pub const MountReleaseRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const MountSterilizeRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const MountToggleRidingRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const MountRenameRequest = struct {
    name: ManagedString = .Empty,
    mount_id: i32 = 0,

    pub const _desc_table = .{
        .name = fd(1, .String),
        .mount_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const MountFeedRequest = struct {
    mount_id: i32 = 0,
    mount_location: MountLocation = @enumFromInt(0),
    mount_food_uid: i32 = 0,
    quantity: i32 = 0,

    pub const _desc_table = .{
        .mount_id = fd(1, .{ .Varint = .Simple }),
        .mount_location = fd(2, .{ .Varint = .Simple }),
        .mount_food_uid = fd(3, .{ .Varint = .Simple }),
        .quantity = fd(4, .{ .Varint = .Simple }),
    };

    pub const MountLocation = enum(i32) {
        EQUIPPED = 0,
        INVENTORY = 1,
        STABLED = 2,
        MAP = 3,
        _,
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const MountSetXpRatioRequest = struct {
    xp_ratio: i32 = 0,

    pub const _desc_table = .{
        .xp_ratio = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const MountInformationRequest = struct {
    mount_id: i32 = 0,
    time: i64 = 0,

    pub const _desc_table = .{
        .mount_id = fd(1, .{ .Varint = .Simple }),
        .time = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const MountInformationInPaddockRequest = struct {
    mount_id: i32 = 0,

    pub const _desc_table = .{
        .mount_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const MountHarnessDissociateRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const MountHarnessColorsUpdateRequest = struct {
    use_harness_colors: bool = false,

    pub const _desc_table = .{
        .use_harness_colors = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const MountSterilizedEvent = struct {
    mount_id: i32 = 0,

    pub const _desc_table = .{
        .mount_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const MountReleasedEvent = struct {
    mount_id: i32 = 0,

    pub const _desc_table = .{
        .mount_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const MountRenamedEvent = struct {
    mount_id: i32 = 0,
    name: ManagedString = .Empty,

    pub const _desc_table = .{
        .mount_id = fd(1, .{ .Varint = .Simple }),
        .name = fd(2, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const MountRenamedErrorEvent = struct {
    mount_id: i32 = 0,

    pub const _desc_table = .{
        .mount_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const MountXpRatioEvent = struct {
    ratio: i32 = 0,

    pub const _desc_table = .{
        .ratio = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const MountDataEvent = struct {
    mount_data: ?com_ankama_dofus_server_game_protocol_common.MountData = null,

    pub const _desc_table = .{
        .mount_data = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const MountDataErrorEvent = struct {
    reason: MountDataError = @enumFromInt(0),

    pub const _desc_table = .{
        .reason = fd(1, .{ .Varint = .Simple }),
    };

    pub const MountDataError = enum(i32) {
        UNKNOWN = 0,
        NOT_FOUND = 1,
        SOMEONE_ELSE_PRIVATE_FARM = 2,
        SOMEONE_ELSE_MOUNT = 3,
        _,
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const MountEquippedEvent = struct {
    mount_data: ?com_ankama_dofus_server_game_protocol_common.MountData = null,

    pub const _desc_table = .{
        .mount_data = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const MountUnequippedEvent = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const MountEquippedErrorEvent = struct {
    @"error": MountEquippedError = @enumFromInt(0),

    pub const _desc_table = .{
        .@"error" = fd(1, .{ .Varint = .Simple }),
    };

    pub const MountEquippedError = enum(i32) {
        UNEQUIPPED = 0,
        EQUIPPED = 1,
        RIDING = 2,
        _,
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const MountRidingEvent = struct {
    is_riding: bool = false,

    pub const _desc_table = .{
        .is_riding = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const MountEmoteIconUsedEvent = struct {
    mount_id: i32 = 0,
    reaction: i32 = 0,

    pub const _desc_table = .{
        .mount_id = fd(1, .{ .Varint = .Simple }),
        .reaction = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const MountUpdateCharacteristicsEvent = struct {
    ride_id: i32 = 0,
    updated_characteristics: ArrayList(MountCharacteristicUpdate),

    pub const _desc_table = .{
        .ride_id = fd(1, .{ .Varint = .Simple }),
        .updated_characteristics = fd(2, .{ .List = .{ .SubMessage = {} } }),
    };

    pub const MountCharacteristicUpdate = struct {
        characteristic: com_ankama_dofus_server_game_protocol_common.MountCharacteristic = @enumFromInt(0),
        int_value: ?i32 = null,

        pub const _desc_table = .{
            .characteristic = fd(1, .{ .Varint = .Simple }),
            .int_value = fd(2, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const DisplayNumericalValuePaddockEvent = struct {
    mount_id: i32 = 0,
    value: i32 = 0,
    type: com_ankama_dofus_server_game_protocol_common.MountCharacteristic = @enumFromInt(0),

    pub const _desc_table = .{
        .mount_id = fd(1, .{ .Varint = .Simple }),
        .value = fd(2, .{ .Varint = .Simple }),
        .type = fd(3, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
