// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.paddock
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
/// import package com.ankama.dofus.server.game.protocol.common
const com_ankama_dofus_server_game_protocol_common = @import("common.pb.zig");

pub const PaddockSellRequest = struct {
    price: i64 = 0,
    for_sale: bool = false,

    pub const _desc_table = .{
        .price = fd(1, .{ .Varint = .Simple }),
        .for_sale = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PaddockBuyRequest = struct {
    proposed_price: i64 = 0,

    pub const _desc_table = .{
        .proposed_price = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PaddockRemoveItemRequest = struct {
    cell_id: i32 = 0,

    pub const _desc_table = .{
        .cell_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PaddockMoveItemRequest = struct {
    old_cell_id: i32 = 0,
    new_cell_id: i32 = 0,

    pub const _desc_table = .{
        .old_cell_id = fd(1, .{ .Varint = .Simple }),
        .new_cell_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PaddocksToSellRequest = struct {
    page_index: i32 = 0,

    pub const _desc_table = .{
        .page_index = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PaddocksToSellFiltersRequest = struct {
    area_id: i32 = 0,
    at_least_mount_number: i32 = 0,
    at_least_machine_number: i32 = 0,
    price_max: i64 = 0,
    order_by: com_ankama_dofus_server_game_protocol_common.RealEstateOrder = @enumFromInt(0),

    pub const _desc_table = .{
        .area_id = fd(1, .{ .Varint = .Simple }),
        .at_least_mount_number = fd(2, .{ .Varint = .Simple }),
        .at_least_machine_number = fd(3, .{ .Varint = .Simple }),
        .price_max = fd(4, .{ .Varint = .Simple }),
        .order_by = fd(5, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PaddockObjectRemovedEvent = struct {
    cell_id: i32 = 0,

    pub const _desc_table = .{
        .cell_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PaddockObjectAddedEvent = struct {
    paddock_item: ?com_ankama_dofus_server_game_protocol_common.ObjectInRolePlay = null,

    pub const _desc_table = .{
        .paddock_item = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PaddockObjectsAddedEvent = struct {
    paddock_item: ArrayList(com_ankama_dofus_server_game_protocol_common.ObjectInRolePlay),

    pub const _desc_table = .{
        .paddock_item = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PaddockBuyResultEvent = struct {
    paddock_id: i64 = 0,
    bought: bool = false,
    price: i64 = 0,

    pub const _desc_table = .{
        .paddock_id = fd(1, .{ .Varint = .Simple }),
        .bought = fd(2, .{ .Varint = .Simple }),
        .price = fd(3, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PaddockPropertiesEvent = struct {
    properties: ?com_ankama_dofus_server_game_protocol_common.PaddockInformation = null,

    pub const _desc_table = .{
        .properties = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PaddockTransactionDialogEvent = struct {
    transaction: Transaction = @enumFromInt(0),
    owner_id: i32 = 0,
    price: i64 = 0,

    pub const _desc_table = .{
        .transaction = fd(1, .{ .Varint = .Simple }),
        .owner_id = fd(2, .{ .Varint = .Simple }),
        .price = fd(3, .{ .Varint = .Simple }),
    };

    pub const Transaction = enum(i32) {
        BUY = 0,
        SELL = 1,
        _,
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PaddockObjectAnimationPlayEvent = struct {
    cells_id: ArrayList(i32),

    pub const _desc_table = .{
        .cells_id = fd(1, .{ .PackedList = .{ .Varint = .Simple } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PaddocksToSellEvent = struct {
    page_index: i32 = 0,
    page_total: i32 = 0,
    paddocks: ArrayList(PaddockForSale),

    pub const _desc_table = .{
        .page_index = fd(1, .{ .Varint = .Simple }),
        .page_total = fd(2, .{ .Varint = .Simple }),
        .paddocks = fd(3, .{ .List = .{ .SubMessage = {} } }),
    };

    pub const PaddockForSale = struct {
        guild_owner: ManagedString = .Empty,
        coordinates: ?com_ankama_dofus_server_game_protocol_common.MapCoordinates = null,
        sub_area_id: i32 = 0,
        mount_number: i32 = 0,
        object_number: i32 = 0,
        price: i64 = 0,

        pub const _desc_table = .{
            .guild_owner = fd(1, .String),
            .coordinates = fd(2, .{ .SubMessage = {} }),
            .sub_area_id = fd(3, .{ .Varint = .Simple }),
            .mount_number = fd(4, .{ .Varint = .Simple }),
            .object_number = fd(5, .{ .Varint = .Simple }),
            .price = fd(6, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
