// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.party
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
/// import package com.ankama.dofus.server.game.protocol.common
const com_ankama_dofus_server_game_protocol_common = @import("common.pb.zig");

pub const PartyMemberInFightCause = enum(i32) {
    UNKNOWN = 0,
    MONSTER_ATTACK = 1,
    PLAYER_ATTACK = 2,
    MEMBER_ATTACKED_PLAYERS = 3,
    MEMBER_CHALLENGE = 4,
    _,
};

pub const PartyType = enum(i32) {
    UNDEFINED = 0,
    CLASSICAL = 1,
    ARENA = 2,
    _,
};

pub const PartyInvitationRequest = struct {
    target: ?com_ankama_dofus_server_game_protocol_common.PlayerSearch = null,
    party_type: PartyType = @enumFromInt(0),

    pub const _desc_table = .{
        .target = fd(1, .{ .SubMessage = {} }),
        .party_type = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyInvitationDetailsRequest = struct {
    party_id: i32 = 0,

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyInvitationAcceptRequest = struct {
    party_id: i32 = 0,

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyInvitationRefuseRequest = struct {
    party_id: i32 = 0,

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyInvitationCancelRequest = struct {
    party_id: i32 = 0,
    guest_id: i64 = 0,

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
        .guest_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyAbdicateThroneRequest = struct {
    party_id: i32 = 0,
    player_id: i64 = 0,

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
        .player_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyFollowMemberRequest = struct {
    party_id: i32 = 0,
    player_id: i64 = 0,
    enabled: ?bool = null,

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
        .player_id = fd(2, .{ .Varint = .Simple }),
        .enabled = fd(3, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyStopFollowMemberRequest = struct {
    party_id: i32 = 0,
    player_id: i64 = 0,

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
        .player_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyLocateMembersRequest = struct {
    party_id: i32 = 0,

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyLeaveRequest = struct {
    party_id: i32 = 0,

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyKickRequest = struct {
    party_id: i32 = 0,
    player_id: i64 = 0,

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
        .player_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyPledgeLoyaltyRequest = struct {
    party_id: i32 = 0,
    loyal: bool = false,

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
        .loyal = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyNameSetRequest = struct {
    party_id: i32 = 0,
    name: ManagedString = .Empty,

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
        .name = fd(2, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyInvitationEvent = struct {
    party_id: i32 = 0,
    party_type: PartyType = @enumFromInt(0),
    party_name: ManagedString = .Empty,
    max_participants: i32 = 0,
    from_player_id: i64 = 0,
    from_player_name: ManagedString = .Empty,
    to_player_id: i64 = 0,

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
        .party_type = fd(2, .{ .Varint = .Simple }),
        .party_name = fd(3, .String),
        .max_participants = fd(4, .{ .Varint = .Simple }),
        .from_player_id = fd(5, .{ .Varint = .Simple }),
        .from_player_name = fd(6, .String),
        .to_player_id = fd(7, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyInvitationDetailsEvent = struct {
    party_id: i32 = 0,
    party_type: PartyType = @enumFromInt(0),
    party_name: ManagedString = .Empty,
    from_player_id: i64 = 0,
    from_player_name: ManagedString = .Empty,
    leader_id: i64 = 0,
    members: ArrayList(com_ankama_dofus_server_game_protocol_common.Character),
    guests: ArrayList(PartyGuest),

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
        .party_type = fd(2, .{ .Varint = .Simple }),
        .party_name = fd(3, .String),
        .from_player_id = fd(4, .{ .Varint = .Simple }),
        .from_player_name = fd(5, .String),
        .leader_id = fd(6, .{ .Varint = .Simple }),
        .members = fd(7, .{ .List = .{ .SubMessage = {} } }),
        .guests = fd(8, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyInvitationCancelledForGuestEvent = struct {
    party_id: i32 = 0,
    canceller_id: i64 = 0,

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
        .canceller_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyInvitationCancelledEvent = struct {
    party_id: i32 = 0,
    canceller_id: i64 = 0,
    guest_id: i64 = 0,

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
        .canceller_id = fd(2, .{ .Varint = .Simple }),
        .guest_id = fd(3, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyInvitationRefusedEvent = struct {
    party_id: i32 = 0,
    guest_id: i64 = 0,

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
        .guest_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyJoinErrorEvent = struct {
    party_id: i32 = 0,
    reason: PartyJoinError = @enumFromInt(0),

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
        .reason = fd(2, .{ .Varint = .Simple }),
    };

    pub const PartyJoinError = enum(i32) {
        UNKNOWN = 0,
        PLAYER_NOT_FOUND = 1,
        PARTY_NOT_FOUND = 2,
        PARTY_FULL = 3,
        PLAYER_BUSY = 4,
        PLAYER_ALREADY_INVITED = 5,
        PLAYER_TOO_SOLICITED = 6,
        PLAYER_LOYAL = 7,
        UNMODIFIABLE = 8,
        UNMET_CRITERION = 9,
        NOT_ENOUGH_ROOM = 10,
        COMPOSITION_CHANGED = 11,
        PLAYER_IN_TUTORIAL = 12,
        _,
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyJoinEvent = struct {
    party_id: i32 = 0,
    party_type: PartyType = @enumFromInt(0),
    leader_id: i64 = 0,
    max_participants: i32 = 0,
    members: ArrayList(com_ankama_dofus_server_game_protocol_common.Character),
    guests: ArrayList(PartyGuest),
    restricted: bool = false,
    party_name: ManagedString = .Empty,

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
        .party_type = fd(2, .{ .Varint = .Simple }),
        .leader_id = fd(3, .{ .Varint = .Simple }),
        .max_participants = fd(4, .{ .Varint = .Simple }),
        .members = fd(5, .{ .List = .{ .SubMessage = {} } }),
        .guests = fd(6, .{ .List = .{ .SubMessage = {} } }),
        .restricted = fd(7, .{ .Varint = .Simple }),
        .party_name = fd(8, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyNewGuestEvent = struct {
    party_id: i32 = 0,
    guest: ?PartyGuest = null,

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
        .guest = fd(2, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyMemberUpdateEvent = struct {
    party_id: i32 = 0,
    member: ?com_ankama_dofus_server_game_protocol_common.Character = null,

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
        .member = fd(2, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyNewMemberEvent = struct {
    party_id: i32 = 0,
    member: ?com_ankama_dofus_server_game_protocol_common.Character = null,

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
        .member = fd(2, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyMemberUpdateLightEvent = struct {
    party_id: i32 = 0,
    player_id: i64 = 0,
    commons_information: ?com_ankama_dofus_server_game_protocol_common.PartyUpdateCommonsInformation = null,
    index: ?i32 = null,

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
        .player_id = fd(2, .{ .Varint = .Simple }),
        .commons_information = fd(3, .{ .SubMessage = {} }),
        .index = fd(4, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyMemberRemoveEvent = struct {
    party_id: i32 = 0,
    leaving_player_id: i64 = 0,
    kicker_id: ?i64 = null,

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
        .leaving_player_id = fd(2, .{ .Varint = .Simple }),
        .kicker_id = fd(3, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyLeaderUpdateEvent = struct {
    party_id: i32 = 0,
    party_leader_id: i64 = 0,

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
        .party_leader_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyFollowStatusUpdateEvent = struct {
    party_id: i32 = 0,
    success: bool = false,
    is_followed: bool = false,
    followed_id: i64 = 0,

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
        .success = fd(2, .{ .Varint = .Simple }),
        .is_followed = fd(3, .{ .Varint = .Simple }),
        .followed_id = fd(4, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyLeaveEvent = struct {
    party_id: i32 = 0,

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyKickedByEvent = struct {
    party_id: i32 = 0,
    kicker_id: i64 = 0,

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
        .kicker_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyRestrictedEvent = struct {
    party_id: i32 = 0,
    restricted: bool = false,

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
        .restricted = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyDeletedEvent = struct {
    party_id: i32 = 0,

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyLoyaltyStatusEvent = struct {
    party_id: i32 = 0,
    loyal: bool = false,

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
        .loyal = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyMemberInFightEvent = struct {
    party_id: i32 = 0,
    reason: PartyMemberInFightCause = @enumFromInt(0),
    member_id: i64 = 0,
    member_account_id: i64 = 0,
    member_name: ManagedString = .Empty,
    fight_id: i32 = 0,
    time_before_fight_start: i32 = 0,
    standard_fight_map: ?com_ankama_dofus_server_game_protocol_common.MapExtendedCoordinates = null,

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
        .reason = fd(2, .{ .Varint = .Simple }),
        .member_id = fd(3, .{ .Varint = .Simple }),
        .member_account_id = fd(4, .{ .Varint = .Simple }),
        .member_name = fd(5, .String),
        .fight_id = fd(6, .{ .Varint = .Simple }),
        .time_before_fight_start = fd(7, .{ .Varint = .Simple }),
        .standard_fight_map = fd(8, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyMemberInBreachFightEvent = struct {
    party_id: i32 = 0,
    reason: PartyMemberInFightCause = @enumFromInt(0),
    member_id: i64 = 0,
    member_account_id: i64 = 0,
    member_name: ManagedString = .Empty,
    fight_id: i32 = 0,
    time_before_fight_start: i32 = 0,
    floor: i32 = 0,
    room: i32 = 0,

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
        .reason = fd(2, .{ .Varint = .Simple }),
        .member_id = fd(3, .{ .Varint = .Simple }),
        .member_account_id = fd(4, .{ .Varint = .Simple }),
        .member_name = fd(5, .String),
        .fight_id = fd(6, .{ .Varint = .Simple }),
        .time_before_fight_start = fd(7, .{ .Varint = .Simple }),
        .floor = fd(8, .{ .Varint = .Simple }),
        .room = fd(9, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyNameUpdateEvent = struct {
    party_id: i32 = 0,
    name: ManagedString = .Empty,

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
        .name = fd(2, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyNameSetErrorEvent = struct {
    party_id: i32 = 0,
    result: PartyNameError = @enumFromInt(0),

    pub const _desc_table = .{
        .party_id = fd(1, .{ .Varint = .Simple }),
        .result = fd(2, .{ .Varint = .Simple }),
    };

    pub const PartyNameError = enum(i32) {
        UNDEFINED_ERROR = 0,
        INVALID = 1,
        ALREADY_USED = 2,
        UNALLOWED_RIGHTS = 3,
        UNALLOWED_NOW = 4,
        _,
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PartyGuest = struct {
    player_id: i64 = 0,
    host_id: i64 = 0,
    name: ManagedString = .Empty,
    look: ?com_ankama_dofus_server_game_protocol_common.EntityLook = null,
    breed: i32 = 0,
    gender: com_ankama_dofus_server_game_protocol_common.Gender = @enumFromInt(0),
    status: ?com_ankama_dofus_server_game_protocol_common.CharacterStatus = null,
    entities: ArrayList(com_ankama_dofus_server_game_protocol_common.PartyEntity),

    pub const _desc_table = .{
        .player_id = fd(1, .{ .Varint = .Simple }),
        .host_id = fd(2, .{ .Varint = .Simple }),
        .name = fd(3, .String),
        .look = fd(4, .{ .SubMessage = {} }),
        .breed = fd(5, .{ .Varint = .Simple }),
        .gender = fd(6, .{ .Varint = .Simple }),
        .status = fd(7, .{ .SubMessage = {} }),
        .entities = fd(8, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
