// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.prism
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
/// import package com.ankama.dofus.server.game.protocol.common
const com_ankama_dofus_server_game_protocol_common = @import("common.pb.zig");

pub const PrismTeleportationRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PrismAttackRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PrismExchangeRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PrismRecycleRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PrismListEvent = struct {
    prism_localized_information: ArrayList(com_ankama_dofus_server_game_protocol_common.PrismLocalizedInformation),

    pub const _desc_table = .{
        .prism_localized_information = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PrismAddOrUpdateEvent = struct {
    prism_localized_information: ?com_ankama_dofus_server_game_protocol_common.PrismLocalizedInformation = null,

    pub const _desc_table = .{
        .prism_localized_information = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PrismRemoveEvent = struct {
    prism_localized_information: ?com_ankama_dofus_server_game_protocol_common.PrismLocalizedInformation = null,

    pub const _desc_table = .{
        .prism_localized_information = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PrismAttackedEvent = struct {
    prism_localized_information: ?com_ankama_dofus_server_game_protocol_common.PrismLocalizedInformation = null,

    pub const _desc_table = .{
        .prism_localized_information = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PrismAttackResultEvent = struct {
    prism_localized_information: ?com_ankama_dofus_server_game_protocol_common.PrismLocalizedInformation = null,
    prism_attack_result: PrismAttackResult = @enumFromInt(0),

    pub const _desc_table = .{
        .prism_localized_information = fd(1, .{ .SubMessage = {} }),
        .prism_attack_result = fd(2, .{ .Varint = .Simple }),
    };

    pub const PrismAttackResult = enum(i32) {
        DEFENDERS_WIN = 0,
        ATTACKERS_WIN = 1,
        _,
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
