// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.roleplay
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
/// import package com.ankama.dofus.server.game.protocol.common
const com_ankama_dofus_server_game_protocol_common = @import("common.pb.zig");

pub const PlayerFightRequest = struct {
    target_id: i64 = 0,
    target_cell_id: i32 = 0,
    friendly: bool = false,

    pub const _desc_table = .{
        .target_id = fd(1, .{ .Varint = .Simple }),
        .target_cell_id = fd(2, .{ .Varint = .Simple }),
        .friendly = fd(3, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PlayerFightFriendlyAnswerRequest = struct {
    fight_id: i32 = 0,
    accept: bool = false,

    pub const _desc_table = .{
        .fight_id = fd(1, .{ .Varint = .Simple }),
        .accept = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AttackMonsterRequest = struct {
    monster_group_id: i64 = 0,

    pub const _desc_table = .{
        .monster_group_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ExitRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const DelayedActionCancelRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const FightRequestCanceledEvent = struct {
    fight_id: i32 = 0,
    source_id: i64 = 0,
    target_id: i64 = 0,

    pub const _desc_table = .{
        .fight_id = fd(1, .{ .Varint = .Simple }),
        .source_id = fd(2, .{ .Varint = .Simple }),
        .target_id = fd(3, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AggressionEvent = struct {
    attacker_id: i64 = 0,
    defender_id: i64 = 0,

    pub const _desc_table = .{
        .attacker_id = fd(1, .{ .Varint = .Simple }),
        .defender_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PlayerFightFriendlyRequestedEvent = struct {
    fight_id: i32 = 0,
    source_id: i64 = 0,
    target_id: i64 = 0,

    pub const _desc_table = .{
        .fight_id = fd(1, .{ .Varint = .Simple }),
        .source_id = fd(2, .{ .Varint = .Simple }),
        .target_id = fd(3, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const PlayerFightFriendlyAnsweredEvent = struct {
    fight_id: i32 = 0,
    source_id: i64 = 0,
    target_id: i64 = 0,
    accept: bool = false,

    pub const _desc_table = .{
        .fight_id = fd(1, .{ .Varint = .Simple }),
        .source_id = fd(2, .{ .Varint = .Simple }),
        .target_id = fd(3, .{ .Varint = .Simple }),
        .accept = fd(4, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const MonsterAngryAtPlayerEvent = struct {
    character_id: i64 = 0,
    monster_group_id: i64 = 0,
    angry_start_time: i64 = 0,
    attack_time: i64 = 0,

    pub const _desc_table = .{
        .character_id = fd(1, .{ .Varint = .Simple }),
        .monster_group_id = fd(2, .{ .Varint = .Simple }),
        .angry_start_time = fd(3, .{ .Varint = .Simple }),
        .attack_time = fd(4, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const MonsterNotAngryAtPlayerEvent = struct {
    character_id: i64 = 0,
    monster_group_id: i64 = 0,

    pub const _desc_table = .{
        .character_id = fd(1, .{ .Varint = .Simple }),
        .monster_group_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ShowChallengeEvent = struct {
    fight_information: ?com_ankama_dofus_server_game_protocol_common.FightCommonInformation = null,

    pub const _desc_table = .{
        .fight_information = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const RemoveChallengeEvent = struct {
    fight_id: i32 = 0,

    pub const _desc_table = .{
        .fight_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const SpellAnimEvent = struct {
    caster_id: i64 = 0,
    target_cell_id: i32 = 0,
    spell_id: i32 = 0,
    spell_level: i32 = 0,
    direction: com_ankama_dofus_server_game_protocol_common.Direction = @enumFromInt(0),

    pub const _desc_table = .{
        .caster_id = fd(1, .{ .Varint = .Simple }),
        .target_cell_id = fd(2, .{ .Varint = .Simple }),
        .spell_id = fd(3, .{ .Varint = .Simple }),
        .spell_level = fd(4, .{ .Varint = .Simple }),
        .direction = fd(5, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const DelayedActionEvent = struct {
    character_id: i64 = 0,
    delayed_action_type: com_ankama_dofus_server_game_protocol_common.DelayedActionType = @enumFromInt(0),
    delayed_end_time: i64 = 0,
    object_gid: ?i32 = null,

    pub const _desc_table = .{
        .character_id = fd(1, .{ .Varint = .Simple }),
        .delayed_action_type = fd(2, .{ .Varint = .Simple }),
        .delayed_end_time = fd(3, .{ .Varint = .Simple }),
        .object_gid = fd(4, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const DelayedActionFinishedEvent = struct {
    character_id: i64 = 0,
    delayed_action_type: com_ankama_dofus_server_game_protocol_common.DelayedActionType = @enumFromInt(0),

    pub const _desc_table = .{
        .character_id = fd(1, .{ .Varint = .Simple }),
        .delayed_action_type = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
