// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.security
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;

pub const CheckType = enum(i32) {
    LENGTH = 0,
    HASH_SUM = 1,
    _,
};

pub const FileCheckRequest = struct {
    check_type: CheckType = @enumFromInt(0),
    value: ManagedString = .Empty,

    pub const _desc_table = .{
        .check_type = fd(1, .{ .Varint = .Simple }),
        .value = fd(2, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TrustStatusEvent = struct {
    certified: bool = false,

    pub const _desc_table = .{
        .certified = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const FileCheckEvent = struct {
    file_name: ManagedString = .Empty,
    check_type: CheckType = @enumFromInt(0),

    pub const _desc_table = .{
        .file_name = fd(1, .String),
        .check_type = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
