// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.shop
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
/// import package com.ankama.dofus.server.game.protocol.common
const com_ankama_dofus_server_game_protocol_common = @import("common.pb.zig");

pub const AccessoryPreviewRequest = struct {
    object_gid: ArrayList(i32),
    show_current_objects: bool = false,

    pub const _desc_table = .{
        .object_gid = fd(1, .{ .PackedList = .{ .Varint = .Simple } }),
        .show_current_objects = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AccessoryPreviewErrorEvent = struct {
    @"error": AccessoryPreviewError = @enumFromInt(0),

    pub const _desc_table = .{
        .@"error" = fd(1, .{ .Varint = .Simple }),
    };

    pub const AccessoryPreviewError = enum(i32) {
        ERROR = 0,
        COOL_DOWN = 1,
        BAD_ITEM = 2,
        _,
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const AccessoryPreviewEvent = struct {
    look: ?com_ankama_dofus_server_game_protocol_common.EntityLook = null,

    pub const _desc_table = .{
        .look = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
