// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.spell
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
/// import package com.ankama.dofus.server.game.protocol.common
const com_ankama_dofus_server_game_protocol_common = @import("common.pb.zig");

pub const SpellVariantActivationRequest = struct {
    spell_id: i32 = 0,

    pub const _desc_table = .{
        .spell_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ForgettableSpellActionRequest = struct {
    spell_id: i32 = 0,
    action: ForgettableSpellAction = @enumFromInt(0),

    pub const _desc_table = .{
        .spell_id = fd(1, .{ .Varint = .Simple }),
        .action = fd(2, .{ .Varint = .Simple }),
    };

    pub const ForgettableSpellAction = enum(i32) {
        FORGET = 0,
        EQUIP = 1,
        REMOVE = 2,
        _,
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ApplySpellModifierEvent = struct {
    actor_id: i64 = 0,
    modifier: ?com_ankama_dofus_server_game_protocol_common.SpellModifier = null,

    pub const _desc_table = .{
        .actor_id = fd(1, .{ .Varint = .Simple }),
        .modifier = fd(2, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const RemoveSpellModifierEvent = struct {
    actor_id: i64 = 0,
    action_type: com_ankama_dofus_server_game_protocol_common.SpellModifierActionType = @enumFromInt(0),
    modifier_type: com_ankama_dofus_server_game_protocol_common.SpellModifierType = @enumFromInt(0),
    spell_id: i32 = 0,

    pub const _desc_table = .{
        .actor_id = fd(1, .{ .Varint = .Simple }),
        .action_type = fd(2, .{ .Varint = .Simple }),
        .modifier_type = fd(3, .{ .Varint = .Simple }),
        .spell_id = fd(4, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const SpellVariantActivationEvent = struct {
    spell_id: i32 = 0,
    effective: bool = false,

    pub const _desc_table = .{
        .spell_id = fd(1, .{ .Varint = .Simple }),
        .effective = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ForgettableSpellEquipmentSlotsEvent = struct {
    quantity: i32 = 0,

    pub const _desc_table = .{
        .quantity = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ForgettableSpellDeletionEvent = struct {
    reason: DeletionReason = @enumFromInt(0),
    spells: ArrayList(i32),

    pub const _desc_table = .{
        .reason = fd(1, .{ .Varint = .Simple }),
        .spells = fd(2, .{ .PackedList = .{ .Varint = .Simple } }),
    };

    pub const DeletionReason = enum(i32) {
        UNKNOWN = 0,
        ADMIN_COMMAND_REQUEST = 1,
        FORGOTTEN = 2,
        DISABLED = 3,
        NOT_FOUND = 4,
        _,
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ForgettableSpellsEvent = struct {
    action: Action = @enumFromInt(0),
    spells: ArrayList(SpellItem),

    pub const _desc_table = .{
        .action = fd(1, .{ .Varint = .Simple }),
        .spells = fd(2, .{ .List = .{ .SubMessage = {} } }),
    };

    pub const Action = enum(i32) {
        DISPATCH = 0,
        UPDATE = 1,
        _,
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const SpellsEvent = struct {
    spell_visualisation: bool = false,
    human_spells: ArrayList(SpellItem),
    mutant_spells: ArrayList(SpellItem),

    pub const _desc_table = .{
        .spell_visualisation = fd(1, .{ .Varint = .Simple }),
        .human_spells = fd(2, .{ .List = .{ .SubMessage = {} } }),
        .mutant_spells = fd(3, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const SpellItem = struct {
    spell_id: i32 = 0,
    spell_level: i32 = 0,
    available: ?bool = null,

    pub const _desc_table = .{
        .spell_id = fd(1, .{ .Varint = .Simple }),
        .spell_level = fd(2, .{ .Varint = .Simple }),
        .available = fd(3, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
