// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.suggestion
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;

pub const ActivitySuggestionsRequest = struct {
    min_level: i32 = 0,
    max_level: i32 = 0,
    area_id: i32 = 0,
    activity_category_id: i32 = 0,
    cards_number: i32 = 0,

    pub const _desc_table = .{
        .min_level = fd(1, .{ .Varint = .Simple }),
        .max_level = fd(2, .{ .Varint = .Simple }),
        .area_id = fd(3, .{ .Varint = .Simple }),
        .activity_category_id = fd(4, .{ .Varint = .Simple }),
        .cards_number = fd(5, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ActivityHideRequest = struct {
    activity_id: i32 = 0,

    pub const _desc_table = .{
        .activity_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ActivityLockRequest = struct {
    activity_id: i32 = 0,

    pub const _desc_table = .{
        .activity_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const ActivitySuggestionsEvent = struct {
    locked_activities: ArrayList(i32),
    unlocked_activities: ArrayList(i32),

    pub const _desc_table = .{
        .locked_activities = fd(1, .{ .PackedList = .{ .Varint = .Simple } }),
        .unlocked_activities = fd(2, .{ .PackedList = .{ .Varint = .Simple } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
