// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.symbiont
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;

pub const MimicryResult = enum(i32) {
    ERROR = 0,
    PLAYER_BUSY = 1,
    HOST_NOT_MIMICKABLE = 2,
    HOST_WRAPPED = 3,
    DUPLICATE = 4,
    SUCCESS = 5,
    _,
};

pub const WrapperObjectDissociateRequest = struct {
    host_uid: i32 = 0,
    host_position: i32 = 0,

    pub const _desc_table = .{
        .host_uid = fd(1, .{ .Varint = .Simple }),
        .host_position = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const MimicryRequest = struct {
    symbiont_uid: i32 = 0,
    host_uid: i32 = 0,

    pub const _desc_table = .{
        .symbiont_uid = fd(1, .{ .Varint = .Simple }),
        .host_uid = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const MimicryResponse = struct {
    result: MimicryResult = @enumFromInt(0),

    pub const _desc_table = .{
        .result = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const MimicryFreeRequest = struct {
    host_uid: i32 = 0,

    pub const _desc_table = .{
        .host_uid = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const MimicryFreeResponse = struct {
    result: MimicryResult = @enumFromInt(0),

    pub const _desc_table = .{
        .result = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
