// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.taxcollector
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
/// import package com.ankama.dofus.server.game.protocol.common
const com_ankama_dofus_server_game_protocol_common = @import("common.pb.zig");

pub const TaxCollectorUpdatesListenStartRequest = struct {
    tax_collector_uid: ManagedString = .Empty,

    pub const _desc_table = .{
        .tax_collector_uid = fd(1, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TaxCollectorUpdatesListenStopRequest = struct {
    tax_collector_uid: ManagedString = .Empty,

    pub const _desc_table = .{
        .tax_collector_uid = fd(1, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TaxCollectorOrderedSpellAddRequest = struct {
    tax_collector_uid: ManagedString = .Empty,
    added_spell: ?com_ankama_dofus_server_game_protocol_common.TaxCollectorOrderedSpell = null,

    pub const _desc_table = .{
        .tax_collector_uid = fd(1, .String),
        .added_spell = fd(2, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TaxCollectorOrderedSpellRemoveRequest = struct {
    tax_collector_uid: ManagedString = .Empty,
    slot_id: i32 = 0,

    pub const _desc_table = .{
        .tax_collector_uid = fd(1, .String),
        .slot_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TaxCollectorOrderedSpellMoveRequest = struct {
    tax_collector_uid: ManagedString = .Empty,
    from_slot_id: i32 = 0,
    to_slot_id: i32 = 0,

    pub const _desc_table = .{
        .tax_collector_uid = fd(1, .String),
        .from_slot_id = fd(2, .{ .Varint = .Simple }),
        .to_slot_id = fd(3, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TaxCollectorPresetsUpdatesListenStartRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TaxCollectorPresetsUpdatesListenStopRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TaxCollectorPresetSpellAddRequest = struct {
    preset_uid: ManagedString = .Empty,
    spell: ?com_ankama_dofus_server_game_protocol_common.TaxCollectorOrderedSpell = null,

    pub const _desc_table = .{
        .preset_uid = fd(1, .String),
        .spell = fd(2, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TaxCollectorPresetSpellRemoveRequest = struct {
    preset_uid: ManagedString = .Empty,
    slot_id: i32 = 0,

    pub const _desc_table = .{
        .preset_uid = fd(1, .String),
        .slot_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TaxCollectorPresetSpellMoveRequest = struct {
    preset_uid: ManagedString = .Empty,
    from_slot_id: i32 = 0,
    to_slot_id: i32 = 0,

    pub const _desc_table = .{
        .preset_uid = fd(1, .String),
        .from_slot_id = fd(2, .{ .Varint = .Simple }),
        .to_slot_id = fd(3, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TaxCollectorTopListEvent = struct {
    dungeon_tax_collectors_information: ArrayList(com_ankama_dofus_server_game_protocol_common.TaxCollectorInformation),
    world_tax_collectors_information: ArrayList(com_ankama_dofus_server_game_protocol_common.TaxCollectorInformation),

    pub const _desc_table = .{
        .dungeon_tax_collectors_information = fd(1, .{ .List = .{ .SubMessage = {} } }),
        .world_tax_collectors_information = fd(2, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TaxCollectorStateUpdateEvent = struct {
    tax_collector_uid: ManagedString = .Empty,
    state: com_ankama_dofus_server_game_protocol_common.TaxCollectorState = @enumFromInt(0),

    pub const _desc_table = .{
        .tax_collector_uid = fd(1, .String),
        .state = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TaxCollectorAddedEvent = struct {
    caller_id: i64 = 0,
    tax_collector: ?com_ankama_dofus_server_game_protocol_common.TaxCollectorInformation = null,

    pub const _desc_table = .{
        .caller_id = fd(1, .{ .Varint = .Simple }),
        .tax_collector = fd(2, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TaxCollectorRemovedEvent = struct {
    tax_collector_uid: ManagedString = .Empty,

    pub const _desc_table = .{
        .tax_collector_uid = fd(1, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TaxCollectorAttackedEvent = struct {
    first_name_id: i32 = 0,
    last_name_id: i32 = 0,
    coordinates: ?com_ankama_dofus_server_game_protocol_common.MapExtendedCoordinates = null,
    alliance_uid: ManagedString = .Empty,
    alliance_tag: ManagedString = .Empty,

    pub const _desc_table = .{
        .first_name_id = fd(1, .{ .Varint = .Simple }),
        .last_name_id = fd(2, .{ .Varint = .Simple }),
        .coordinates = fd(3, .{ .SubMessage = {} }),
        .alliance_uid = fd(4, .String),
        .alliance_tag = fd(5, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TaxCollectorAttackResultEvent = struct {
    dead: bool = false,
    first_name_id: i32 = 0,
    last_name_id: i32 = 0,
    coordinates: ?com_ankama_dofus_server_game_protocol_common.MapExtendedCoordinates = null,
    alliance_uid: ManagedString = .Empty,
    alliance_tag: ManagedString = .Empty,

    pub const _desc_table = .{
        .dead = fd(1, .{ .Varint = .Simple }),
        .first_name_id = fd(2, .{ .Varint = .Simple }),
        .last_name_id = fd(3, .{ .Varint = .Simple }),
        .coordinates = fd(4, .{ .SubMessage = {} }),
        .alliance_uid = fd(5, .String),
        .alliance_tag = fd(6, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TaxCollectorHarvestedEvent = struct {
    tax_collector_uid: ManagedString = .Empty,
    harvester_id: i64 = 0,
    harvester_name: ManagedString = .Empty,

    pub const _desc_table = .{
        .tax_collector_uid = fd(1, .String),
        .harvester_id = fd(2, .{ .Varint = .Simple }),
        .harvester_name = fd(3, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TaxCollectorMovement = struct {
    movement_type: TaxCollectorMovementType = @enumFromInt(0),
    first_name_id: i32 = 0,
    last_name_id: i32 = 0,
    coordinates: ?com_ankama_dofus_server_game_protocol_common.MapExtendedCoordinates = null,
    player_id: i64 = 0,
    player_name: ManagedString = .Empty,

    pub const _desc_table = .{
        .movement_type = fd(1, .{ .Varint = .Simple }),
        .first_name_id = fd(2, .{ .Varint = .Simple }),
        .last_name_id = fd(3, .{ .Varint = .Simple }),
        .coordinates = fd(4, .{ .SubMessage = {} }),
        .player_id = fd(5, .{ .Varint = .Simple }),
        .player_name = fd(6, .String),
    };

    pub const TaxCollectorMovementType = enum(i32) {
        TAX_COLLECTOR_UNKNOWN_ACTION = 0,
        TAX_COLLECTOR_HIRED = 1,
        TAX_COLLECTOR_HARVESTED = 2,
        TAX_COLLECTOR_DEFEATED = 3,
        TAX_COLLECTOR_DESTROYED = 4,
        _,
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TaxCollectorMovementsOfflineEvent = struct {
    movements: ArrayList(TaxCollectorMovement),

    pub const _desc_table = .{
        .movements = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TaxCollectorEquipmentUpdateEvent = struct {
    tax_collector_uid: ManagedString = .Empty,
    object: ?com_ankama_dofus_server_game_protocol_common.ObjectItemInventory = null,
    added: bool = false,
    characteristics: ArrayList(com_ankama_dofus_server_game_protocol_common.CharacterCharacteristic),

    pub const _desc_table = .{
        .tax_collector_uid = fd(1, .String),
        .object = fd(2, .{ .SubMessage = {} }),
        .added = fd(3, .{ .Varint = .Simple }),
        .characteristics = fd(4, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TaxCollectorErrorEvent = struct {
    reason: TaxCollectorErrorReason = @enumFromInt(0),

    pub const _desc_table = .{
        .reason = fd(1, .{ .Varint = .Simple }),
    };

    pub const TaxCollectorErrorReason = enum(i32) {
        TAX_COLLECTOR_ERROR_UNKNOWN = 0,
        TAX_COLLECTOR_NOT_FOUND = 1,
        TAX_COLLECTOR_NOT_OWNED = 2,
        TAX_COLLECTOR_NO_RIGHTS = 3,
        TAX_COLLECTOR_MAX_REACHED = 4,
        TAX_COLLECTOR_ALREADY_ONE = 5,
        TAX_COLLECTOR_CANT_HIRE_YET = 6,
        TAX_COLLECTOR_CANT_HIRE_HERE = 7,
        TAX_COLLECTOR_NOT_ENOUGH_KAMAS = 8,
        _,
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TaxCollectorUpdatesListeningConfirmationEvent = struct {
    information: ?com_ankama_dofus_server_game_protocol_common.TaxCollectorInformation = null,

    pub const _desc_table = .{
        .information = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TaxCollectorOrderedSpellUpdatedEvent = struct {
    tax_collector_uid: ManagedString = .Empty,
    spells: ArrayList(com_ankama_dofus_server_game_protocol_common.TaxCollectorOrderedSpell),

    pub const _desc_table = .{
        .tax_collector_uid = fd(1, .String),
        .spells = fd(2, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TaxCollectorPresetsEvent = struct {
    presets: ArrayList(com_ankama_dofus_server_game_protocol_common.TaxCollectorPreset),

    pub const _desc_table = .{
        .presets = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TaxCollectorPresetSpellUpdatedEvent = struct {
    preset_uid: ManagedString = .Empty,
    spells: ArrayList(com_ankama_dofus_server_game_protocol_common.TaxCollectorOrderedSpell),

    pub const _desc_table = .{
        .preset_uid = fd(1, .String),
        .spells = fd(2, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TaxCollectorFightRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};
