// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.tinsel
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;

pub const TinselSelectError = enum(i32) {
    UNDEFINED = 0,
    INVALID = 1,
    ALREADY = 2,
    _,
};

pub const TitlesAndOrnamentsRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TitlesAndOrnamentsEvent = struct {
    titles: ArrayList(i32),
    ornaments: ArrayList(i32),

    pub const _desc_table = .{
        .titles = fd(1, .{ .PackedList = .{ .Varint = .Simple } }),
        .ornaments = fd(2, .{ .PackedList = .{ .Varint = .Simple } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TitleGainedEvent = struct {
    title_id: i32 = 0,

    pub const _desc_table = .{
        .title_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TitleLostEvent = struct {
    title_id: i32 = 0,

    pub const _desc_table = .{
        .title_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const OrnamentGainedEvent = struct {
    ornament_id: i32 = 0,

    pub const _desc_table = .{
        .ornament_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const OrnamentLostEvent = struct {
    ornament_id: i32 = 0,

    pub const _desc_table = .{
        .ornament_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TitleSelectedEvent = struct {
    title_id: i32 = 0,

    pub const _desc_table = .{
        .title_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const TitleSelectErrorEvent = struct {
    reason: TinselSelectError = @enumFromInt(0),

    pub const _desc_table = .{
        .reason = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const OrnamentSelectedEvent = struct {
    ornament_id: i32 = 0,

    pub const _desc_table = .{
        .ornament_id = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const OrnamentSelectErrorEvent = struct {
    reason: TinselSelectError = @enumFromInt(0),

    pub const _desc_table = .{
        .reason = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
