// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.ui
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;

pub const ClientUIOpenedEvent = struct {
    type: UIType = @enumFromInt(0),
    object_uid: ?i32 = null,

    pub const _desc_table = .{
        .type = fd(1, .{ .Varint = .Simple }),
        .object_uid = fd(2, .{ .Varint = .Simple }),
    };

    pub const UIType = enum(i32) {
        UNDEFINED = 0,
        TELEPORT_GUILD_HOUSE = 1,
        TELEPORT_GUILD_PADDOCK = 2,
        OBJECT_MIMICRY = 3,
        LEGENDARY_TREASURE_QUEST = 4,
        TELEPORT_HOUSE = 5,
        _,
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
