// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.interactive.element
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
/// import package com.ankama.dofus.server.game.protocol.common
const com_ankama_dofus_server_game_protocol_common = @import("../common.pb.zig");

pub const InteractiveUseRequest = struct {
    element_id: i32 = 0,
    skill_instance_uid: i32 = 0,
    specific_instance_id: ?i32 = null,

    pub const _desc_table = .{
        .element_id = fd(1, .{ .Varint = .Simple }),
        .skill_instance_uid = fd(2, .{ .Varint = .Simple }),
        .specific_instance_id = fd(3, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const InteractiveUseErrorEvent = struct {
    element_id: i32 = 0,
    skill_instance_uid: i32 = 0,

    pub const _desc_table = .{
        .element_id = fd(1, .{ .Varint = .Simple }),
        .skill_instance_uid = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const InteractiveUsedEvent = struct {
    entity_id: i64 = 0,
    element_id: i32 = 0,
    skill_id: i32 = 0,
    duration: i32 = 0,
    can_move: bool = false,

    pub const _desc_table = .{
        .entity_id = fd(1, .{ .Varint = .Simple }),
        .element_id = fd(2, .{ .Varint = .Simple }),
        .skill_id = fd(3, .{ .Varint = .Simple }),
        .duration = fd(4, .{ .Varint = .Simple }),
        .can_move = fd(5, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const InteractiveUseEndedEvent = struct {
    element_id: i32 = 0,
    skill_id: i32 = 0,

    pub const _desc_table = .{
        .element_id = fd(1, .{ .Varint = .Simple }),
        .skill_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const InteractiveMapUpdateEvent = struct {
    interactive_elements: ArrayList(com_ankama_dofus_server_game_protocol_common.InteractiveElement),

    pub const _desc_table = .{
        .interactive_elements = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const StatedMapUpdateEvent = struct {
    stated_elements: ArrayList(com_ankama_dofus_server_game_protocol_common.StatedElement),

    pub const _desc_table = .{
        .stated_elements = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const InteractiveElementUpdatedEvent = struct {
    interactive_element: ?com_ankama_dofus_server_game_protocol_common.InteractiveElement = null,

    pub const _desc_table = .{
        .interactive_element = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const StatedElementUpdatedEvent = struct {
    stated_element: ?com_ankama_dofus_server_game_protocol_common.StatedElement = null,

    pub const _desc_table = .{
        .stated_element = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
