// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.finish.move
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;

pub const FinishMovesRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const FinishMoveSetRequest = struct {
    finish_move_id: i32 = 0,
    effective: bool = false,

    pub const _desc_table = .{
        .finish_move_id = fd(1, .{ .Varint = .Simple }),
        .effective = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const FinishMovesEvent = struct {
    finish_moves: ArrayList(FinishMove),

    pub const _desc_table = .{
        .finish_moves = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub const FinishMove = struct {
        finish_move_id: i32 = 0,
        effective: bool = false,

        pub const _desc_table = .{
            .finish_move_id = fd(1, .{ .Varint = .Simple }),
            .effective = fd(2, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
