// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.guild.chest
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;

pub const GuildChestTabSelectRequest = struct {
    tab_number: i32 = 0,

    pub const _desc_table = .{
        .tab_number = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const GuildChestTabUpdateRequest = struct {
    tab_number: i32 = 0,
    name: ManagedString = .Empty,
    picto: i32 = 0,
    drop_type_limitation: ArrayList(i32),

    pub const _desc_table = .{
        .tab_number = fd(1, .{ .Varint = .Simple }),
        .name = fd(2, .String),
        .picto = fd(3, .{ .Varint = .Simple }),
        .drop_type_limitation = fd(4, .{ .PackedList = .{ .Varint = .Simple } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const GuildChestTabContributionsRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const GuildChestContributionStartRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const GuildChestContributionStopRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const GuildChestStructureStartListeningRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const GuildChestStructureStopListeningRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const GuildChestTabContributionsEvent = struct {
    contributions: ArrayList(Contribution),

    pub const _desc_table = .{
        .contributions = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub const Contribution = struct {
        contributor_id: i64 = 0,
        contributor_name: ManagedString = .Empty,
        amount: i64 = 0,

        pub const _desc_table = .{
            .contributor_id = fd(1, .{ .Varint = .Simple }),
            .contributor_name = fd(2, .String),
            .amount = fd(3, .{ .Varint = .Simple }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const GuildChestTabLastContributionDateEvent = struct {
    last_contribution_date: i64 = 0,

    pub const _desc_table = .{
        .last_contribution_date = fd(1, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const GuildChestTabContributionEvent = struct {
    tab_number: i32 = 0,
    required_amount: i64 = 0,
    current_amount: i64 = 0,
    chest_contribution_enrollment_delay: i64 = 0,
    chest_contribution_delay: i64 = 0,

    pub const _desc_table = .{
        .tab_number = fd(1, .{ .Varint = .Simple }),
        .required_amount = fd(2, .{ .Varint = .Simple }),
        .current_amount = fd(3, .{ .Varint = .Simple }),
        .chest_contribution_enrollment_delay = fd(4, .{ .Varint = .Simple }),
        .chest_contribution_delay = fd(5, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const GuildChestCurrentListenersEvent = struct {
    players: ArrayList(ManagedString),

    pub const _desc_table = .{
        .players = fd(1, .{ .List = .String }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const GuildChestCurrentListenersAddEvent = struct {
    players: ManagedString = .Empty,

    pub const _desc_table = .{
        .players = fd(1, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const GuildChestCurrentListenersRemoveEvent = struct {
    players: ManagedString = .Empty,

    pub const _desc_table = .{
        .players = fd(1, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
