// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.guild.house
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
/// import package com.ankama.dofus.server.game.protocol.common
const com_ankama_dofus_server_game_protocol_common = @import("../common.pb.zig");

pub const GuildHousesEvent = struct {
    houses: ArrayList(com_ankama_dofus_server_game_protocol_common.House),

    pub const _desc_table = .{
        .houses = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const GuildHouseUpdateEvent = struct {
    house: ?com_ankama_dofus_server_game_protocol_common.House = null,

    pub const _desc_table = .{
        .house = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const GuildHouseRemoveEvent = struct {
    house_id: i32 = 0,
    instance_id: i32 = 0,
    second_hand: bool = false,

    pub const _desc_table = .{
        .house_id = fd(1, .{ .Varint = .Simple }),
        .instance_id = fd(2, .{ .Varint = .Simple }),
        .second_hand = fd(3, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
