// Code generated by protoc-gen-zig
///! package com.ankama.dofus.server.game.protocol.guild.member
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
/// import package com.ankama.dofus.server.game.protocol.common
const com_ankama_dofus_server_game_protocol_common = @import("../common.pb.zig");

pub const GuildMemberParametersChangeRequest = struct {
    member_id: i64 = 0,
    rank_id: i32 = 0,
    experience_given_percent: i32 = 0,

    pub const _desc_table = .{
        .member_id = fd(1, .{ .Varint = .Simple }),
        .rank_id = fd(2, .{ .Varint = .Simple }),
        .experience_given_percent = fd(3, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const GuildMemberWarnOnConnectionStartRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const GuildMemberWarnOnConnectionStopRequest = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const GuildMemberOnlineStatusEvent = struct {
    member_id: i64 = 0,
    online: bool = false,

    pub const _desc_table = .{
        .member_id = fd(1, .{ .Varint = .Simple }),
        .online = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const GuildMembersEvent = struct {
    members: ArrayList(com_ankama_dofus_server_game_protocol_common.Character),

    pub const _desc_table = .{
        .members = fd(1, .{ .List = .{ .SubMessage = {} } }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const GuildMemberUpdateEvent = struct {
    member: ?com_ankama_dofus_server_game_protocol_common.Character = null,

    pub const _desc_table = .{
        .member = fd(1, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const GuildMemberLeaveEvent = struct {
    kicked: bool = false,
    player_id: i64 = 0,

    pub const _desc_table = .{
        .kicked = fd(1, .{ .Varint = .Simple }),
        .player_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const GuildLeftEvent = struct {
    pub const _desc_table = .{};

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const GuildMembershipEvent = struct {
    guild_information: ?com_ankama_dofus_server_game_protocol_common.GuildInformation = null,
    rank_id: i32 = 0,

    pub const _desc_table = .{
        .guild_information = fd(1, .{ .SubMessage = {} }),
        .rank_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const GuildJoinedEvent = struct {
    guild_information: ?com_ankama_dofus_server_game_protocol_common.GuildInformation = null,
    rank_id: i32 = 0,

    pub const _desc_table = .{
        .guild_information = fd(1, .{ .SubMessage = {} }),
        .rank_id = fd(2, .{ .Varint = .Simple }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
